### PR TITLE
LRIS docs fix

### PR DESCRIPTION
**Pull request by SunilSimha**
Bit of a hotfix to clarify the mask info insertion procedure for LRIS. Just changes the docs.

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Thx!  We could send this straight to `release`

**Comment by SunilSimha** [comment]
Should I create a PR to `release` instead of this, then?

**Comment by profxj** [comment]
redirected to `release`

**Comment by SunilSimha** [comment]
Looks like it's pulling in many more `develop` branch commits into `release`. Closing this and reopening one directly to `release`.

**Pull request closed without merging**
