### PR TITLE
Fix duplicate column crash in pypeit_setupSetup dup calib id fix

### PR DESCRIPTION
**Pull request by badpandabear**
This PR fixes a crash in `pypeit_setup` when it is run on `magellan_fire` data  which was reported in the Pypeit Users slack.  It turns out this problem was caused by PR1586 adding `calib_id` to every  setup file. For spectrographs that already included `calib_id`, this would fail with a duplicate column error. The full list of affected spectrographs is: `lbt_luci1`, `lbt_luci2`, `magellan_fire`, `magellan_fire_long`, `p200_tspec`, and `vlt_sinfoni`.

I also merged in the documentation changes from `release` .

I ran unit tests on these changes and am currently running the full dev-suite.

### CODE REVIEW

**Comment by badpandabear** [comment]
Unit test results:
```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  228 passed, 2 skipped, 34 warnings in 122.11s (0:02:02) ---
--- PYTEST UNIT TESTS PASSED  122 passed, 178 warnings in 576.74s (0:09:36) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 0/0 TESTS  ---
Testing Started at 2023-06-12T13:34:59.631055
Testing Completed at 2023-06-12T13:46:39.987966
Total Time: 0:11:40.356911
```

**Review by kbwestfall — APPROVED** [review]
Thanks!  Are there new tests in the dev-suite that check this?

**Comment by badpandabear** [comment]
> Thanks! Are there new tests in the dev-suite that check this?

Not yet :) But I'll add one

**Comment by kbwestfall** [comment]
> > Thanks! Are there new tests in the dev-suite that check this?
> 
> Not yet :) But I'll add one

There are lots of similar tests in `unit_tests/test_setups.py`.  It looks like we missed these instruments, though!

**Review by profxj — APPROVED** [review]
all good

**Comment by badpandabear** [comment]
Dev suite results:
```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  230 passed, 35 warnings in 206.79s (0:03:26) ---
--- PYTEST UNIT TESTS PASSED  121 passed, 177 warnings in 984.74s (0:16:24) ---
--- PYTEST VET TESTS PASSED  42 passed, 8 warnings in 1105.84s (0:18:25) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 190/190 TESTS  ---
Testing Started at 2023-06-12T20:51:25.599401
Testing Completed at 2023-06-13T05:10:17.042176
Total Time: 8:18:51.442775
```

**Pull request merged**
