### PR TITLE
Labels to telluric [debug]: adding +1 for det/order to account for 0-indexing

### PR DESCRIPTION
**Pull request by ntejos**
As stated, just a cosmetic minor thing.

### CODE REVIEW

**Comment by profxj** [comment]
@ntejos -- this has the same multi-file issue as the other.
Might go away after PR #1200 clears, but let's see..

**Comment by profxj** [comment]
And thanks for these!

**Review by profxj — APPROVED** [review]
Looks fine to me

**Review by jhennawi — CHANGES_REQUESTED** [review]
PR will be approved, but you are behind develop. Please pull in develop, and then one it can merge you are clear.

**Pull request merged**
