### PR TITLE
Keck/KCWI BH3 support

### PR DESCRIPTION
**Pull request by rcooke-ast**
As per a request on the User's Slack, this PR adds support for the Keck/KCWI BH3 grating. See the wavelength solution attached.
Screenshot-2024-08-30-at-12 30 01 PM

### CODE REVIEW

**Review by kbwestfall — APPROVED** [review]
Excellent!

**Review by profxj — APPROVED** [review]
excellent!

**Comment by kbwestfall** [comment]
PS - I realized this morning that, in order for this mode to be "supported" we need an example dataset to test in the dev-suite.  Do we have one?

**Comment by rcooke-ast** [comment]
Yep - I'm working on it  :-)

**Comment by rcooke-ast** [comment]
[dev suite](https://github.com/pypeit/PypeIt-development-suite/pull/333) passes, merging

**Pull request merged**
