### PR TITLE
Added support for SOAR/Goodman blue (M1 only)

### PR DESCRIPTION
**Pull request by rcooke-ast**
As titled - this adds support for SOAR/Goodman blue M1, and pushed some code into the parent class.

There is a related PR in the dev suite. For the record, here's the output from the wavelength calibration:
image

### CODE REVIEW

**Review by profxj — CHANGES_REQUESTED** [review]
Thanks for this!

A few minor requests:

1.  Can you update the spectrograph docs to indicate these updates?
2.  Post tests when complete

**Comment by rcooke-ast** [comment]
Tests pass
image

**Review by profxj — APPROVED** [review]
All good

**Review by kbwestfall — APPROVED** [review]
Looks good!

**Pull request merged**
