### PR TITLE
hotfix BPM

### PR DESCRIPTION
**Pull request by rcooke-ast**
If different calibrations use different amplifier settings, then the BPM needs to be specific to the calibration frame. This PR resets the BPM every time a new frame is being generated. It's a bit overkill, but it takes no time at all, and is "safer".

Addresses Issue #1662

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Approved!

We are confident this will pass the DevSuite, right? :)

**Comment by rcooke-ast** [comment]
We are... but I've already started a dev-suite run, just in case  :-)

**Review by kbwestfall — APPROVED** [review]
I think this is okay, but we should run tests.  I did a quick check of the code and I don't think there are any changes made to `msbpm` that need to propagate between functions (so a refresh is good).  This also ensures each bpm is specific to the relevant frame type (not always based on the frame to be calibrated).

**Comment by rcooke-ast** [comment]
Tests pass... Can merge if tox doesn't timeout.

image

**Pull request merged**
