### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by tepickering**
This PR adds a GitHub Actions workflow to perform code-style and integration testing. It's set up to more or less follow what the existing Travis workflow does. A test matrix is set up to run on python versions 3.7 and 3.8 and against different versions of astropy and numpy. The code-style test is modified from what is run on Travis because GitHub Actions doesn't have the same concept of "allow_failures". There are a LOT of code-style errors when pycodestyle is run with the defaults so I use --select=E9 to make it only error when there are significant syntax errors. GitHub Actions defaults to "fail fast" so it's useful having such a tripwire job that will finish quickly, catch obvious problems, and cancel the rest of the jobs if there's an error.

An example of a workflow run can be see at https://github.com/tepickering/PypeIt/actions/runs/362550738.

This is a resubmit of #1080 which was originally forked from `master` instead of `develop`. Easier to start over than cleanup the mess. Cleaner commit history as well.

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Approved!

When would you recommend I turn off Travis?
And please remind me to flip the setting on GitHub that 
requires these tests to pass once this merges into `develop`

**Comment by tepickering** [comment]
the path i would take would be to merge this, tweak the github settings to switch the checks from travis to actions, and then once happy with the results, remove the travis config in another PR. i don't see a need to keep both around since the existing travis config is not doing anything unique to travis.

**Comment by profxj** [comment]
sounds good to me!

**Comment by profxj** [comment]
merging!

**Pull request merged**
