### PR TITLE
Added Gr4 support

### PR DESCRIPTION
**Pull request by rcooke-ast**
Added support for GR4, based on Users Slack request.

image

### CODE REVIEW

**Review by profxj — APPROVED** [review]
thx!  Is there a DevSuite test on the way?

**Comment by rcooke-ast** [comment]
You bet there is! I knew you'd ask - I was just awaiting permission from the user.

**Comment by rcooke-ast** [comment]
Dev-suite test added, and all passes (the failures are because I only ran NTT/EFOSC2):
image

**Review by kbwestfall — APPROVED** [review]
Nice!

**Pull request merged**
