### PR TITLE
Moments hotfix

### PR DESCRIPTION
**Pull request by rcooke-ast**
A pretty minor hotfix (I think)...

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Approving but let's get @kbwestfall 's eyes on this before merging.

**Review by kbwestfall — CHANGES_REQUESTED** [review]
Admittedly, figuring out all the possible input combinations is non-trivial, but this change breaks catching one of the failure modes.  If `col` is 2D, the code interprets that as the user defining specific columns for the calculation for each row.  If `row` is a single integer (i.e., it's length after converting to an array is 1), it makes no sense for `col` to be 2D because there's only one row.  This changes the test to check for the dimensionality of `row`, not it's length.  A change to `if _row.size == 1` might make sense, given:
```
>>> x = numpy.arange(4).reshape(2,2)
>>> x
array([[0, 1],
       [2, 3]])
>>> len(x)
2
```
but earlier checks should catch if `_row` is 2d.

**Comment by rcooke-ast** [comment]
OK - sounds good... Admittedly, I'm using PypeIt's core routines to reduce data from an unsupported instrument, when I encountered this issue (and my proposed change fixed it... I presumed the definitions here should have been symmetric), so let me dive into see what the issue might be and if there's anything I can do to fix it - thanks @kbwestfall!

**Comment by kbwestfall** [comment]
Sounds good, @rcooke-ast .  Let me know if you run into any problems.  It could be there's a use case that's not being caught or passed correctly.

**Comment by rcooke-ast** [comment]
It was an issue on my end, and it's now resolved... closing.

**Pull request closed without merging**
