### PR TITLE
Merges develop into release (1.15.0 tag prep; take 2)

### PR DESCRIPTION
**Pull request by kbwestfall**
As titled.

Docs updated, unit tests pass, dev-suite running.

Relative to the `develop` branch, this also includes:

- Updates to the development doc
- Moves `deprecated/` directory up one level (out of the `pypeit/` directory)

These were discussed during the 29 Jan development telecon.

Please approve but do not merge until I've posted the results of the dev-suite tests.

### CODE REVIEW

**Review by debora-pe — APPROVED** [review]
Thanks @kbwestfall!

**Review by rcooke-ast — APPROVED** [review]
Great!

**Comment by kbwestfall** [comment]
Annoyingly the `staged` dev-suite branch wasn't up-to-date with the HIRES fix.
```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  247 passed, 56 warnings in 555.31s (0:09:15) ---
--- PYTEST UNIT TESTS PASSED  133 passed, 171 warnings in 1027.18s (0:17:07) ---
--- PYTEST VET TESTS FAILED  1 failed, 60 passed, 71 warnings in 5852.40s (1:37:32) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 237/237 TESTS  ---
Testing Started at 2024-02-05T21:26:03.016126
Testing Completed at 2024-02-06T17:33:10.301818
Total Time: 20:07:07.285692
```
I'm now rerunning the relevant dev-suite tests locally.

**Comment by kbwestfall** [comment]
I actually just reran the whole dev-suite.  Tests pass:

```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  247 passed, 56 warnings in 454.39s (0:07:34) ---
--- PYTEST UNIT TESTS PASSED  133 passed, 171 warnings in 1078.38s (0:17:58) ---
--- PYTEST VET TESTS PASSED  61 passed, 69 warnings in 4721.99s (1:18:41) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 237/237 TESTS  ---
Testing Started at 2024-02-06T22:48:09.065156
Testing Completed at 2024-02-07T10:15:08.461811
Total Time: 11:26:59.396655
```

**Pull request merged**
