### PR TITLE
Updated Paranal extinction file

### PR DESCRIPTION
**Pull request by afloers**
## Description
This PR updated the Paranal extinction table used in the creation of the sensitivity curve and the fluxing of spectra observed with the VLT on Cerro Paranal. 

## Motivation and Context
The currently used extinction table is no longer available at the link given in the file. Additionally, it is unclear where the data originates. There is a tension between the currently used extinction data and data published in refereed journals:
Paranal_extinction
The current pypeit extinction curve has a sharp cutoff near 7000A that is in tension with published data as well as FORS2 quality control (see [http://archive.eso.org/qc1/qc1_cgi?action=qc1_plot_table&table=fors2_photometry](http://archive.eso.org/qc1/qc1_cgi?action=qc1_plot_table&table=fors2_photometry) for photometric extinction). 
The new data included ini this PR is taken from [https://www.aanda.org/articles/aa/pdf/2011/03/aa15537-10.pdf](https://www.aanda.org/articles/aa/pdf/2011/03/aa15537-10.pdf) Patat et al., 2011, A&A, 527, A91. This is the most recent spectroscopic study performed by ESO and it's unlikely that the extinction data has changed since then.

## How Has This Been Tested?
This just replaces the currently used extinction data with a more up-to-date version. 
The new data starts at 3325A compared to 3100A, which might require extrapolation for certain configurations.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have assigned/requested two reviewers for this pull request.

### CODE REVIEW

**Review by profxj — CHANGES_REQUESTED** [review]
Thanks for this!

While they may be highly uncertain, we should include 
values down to 3100Ang.  Even if the VLT instruments
don't go quite that blue.  

I suggest you use the lowest 2 values from the previous file.
Thanks.

**Review by feigewang — CHANGES_REQUESTED** [review]
Thanks so much for updating this. Is there a way to extend the longer wavelength part? There are several optical spectrograph can go beyond 1um.

**Review by profxj — APPROVED** [review]
Thanks!

**Review by feigewang — APPROVED** [review]
thanks!

**Comment by profxj** [comment]
merging

**Pull request merged**
