### PR TITLE
Doc hotfixes : Logo and frametype

### PR DESCRIPTION
**Pull request by profxj**
Better clarify frametypes.

Adds logo

### CODE REVIEW

**Review by kbwestfall — APPROVED** [review]
Looks good!  I edited `doc/conf.py` to add the logo to the top of the sidebar, as well.  Is there a reason to put the logo in the `_static` directory instead of `images`?

**Comment by profxj** [comment]
do you mean `figures`, @kbwestfall ?

Not sure where to find `images`.

**Comment by kbwestfall** [comment]
> do you mean `figures`, @kbwestfall ?
> 
> Not sure where to find `images`.

Ah, sorry, yes, I meant `figures`.

**Review by badpandabear — APPROVED** [review]

**Review by rcooke-ast — APPROVED** [review]
Approved

**Pull request merged**
