### PR TITLE
NOT/ALFOSC wavelength fixes

### PR DESCRIPTION
**Pull request by Raindogjones**
-Removes ArII from lamps for all but two grisms.
-Includes improved wavelength solution for grism4
-Adds a three NeI lines (present in NIST) from ALFOSC documentation

### CODE REVIEW

**Review by rcooke-ast — APPROVED** [review]
All good - thanks for the fixes and new setup!!

Is this something you would like to add to the dev suite, for continued support?

**Comment by Raindogjones** [comment]
All of these setups are in the dev suite already.  The issue was that with having ArII in the lamp list, pypeit was misidentifying lines (even ones that are correctly identified in the arxiv solution). So, for the most part, just limiting the lamps and only having ArI and ArII when absolutely necessary improves things (at least for the datasets in the dev suite).

> Is this something you would like to add to the dev suite, for continued support?

**Comment by profxj** [comment]
@Raindogjones -- I'd like to back this up with a set of 
`vet tests` in the DevSuite.

These run after the full reductions and can be used
to,e.g. place restrictions on the RMS of the wavelength fits.

If you were willing to do this yourself, you'd add tests in here:
https://github.com/pypeit/PypeIt-development-suite/tree/master/vet_tests

But I could start the ball rolling or do it for you altogether if you preferred.
Just would need to know the RMS to require for the various grisms

**Review by profxj — CHANGES_REQUESTED** [review]
Thx for this!

Am putting the Request Changes on this
until we resolve vet tests.

I also do worry a touch about adding `Ne I` lines.

@Raindogjones -- are you able to check a few of
the other spectrographs using Ne?  

e.g.  LRISr, Kastr, DEIMOS.
Actually, let me do this by adding vet tests for
those spectrographs and I'll do the `NOT`  too..

**Comment by Raindogjones** [comment]
> Just would need to know the RMS to require for the various grisms

@profxj Would this just be for the data in the dev suite or in general? For the dev suite it should be relatively easy to provide a rough limit, but for any data taken with those grisms it is more challenging.  The lower resolution grisms are often used with wide slits where lines are very undersampled and this generally leads to worse RMS...

**Comment by profxj** [comment]
Yes, just the DevSuite.

This way if we "improve" things with wavelengths, you'll know whether
we degraded the NOT too far.

I'm going to take the lead on this.  Don't worry about it.
But, I'm going to keep the hold on this PR to incentivize
me (yes, that's strange..)  ;)

**Comment by Raindogjones** [comment]
> I'm going to take the lead on this. Don't worry about it.

@profxj Great. Do you still want me to provide some limits, or are you happy to estimate them from the data in the dev suite? 

Along the same lines, maybe it would be worth me trying to find some unbinned data to put in the dev suite for grism4 as this will be a more stringent test of the wavelength calibration...

**Comment by profxj** [comment]
I'll handle it.

But let me know if you add more.  
And if you do, maybe you should do so on the branch I'll be working on..

**Comment by Raindogjones** [comment]
I've dumped some unbinned grism4 data on the gdrive. Let me know what branch you want me to commit the pypeit file to or feel free to create it yourself (it shouldn't need anything special to run other than setting the frametype of the relatively long exptime standard).

**Comment by profxj** [comment]
@Raindogjones , are you on our Developers Slack?
 
If not, may I invite you on?  
Some correspondence is easier that way (e.g. have
questions on the wavecalib).

**Comment by Raindogjones** [comment]
@profxj Have messaged you on the slack.

**Review by profxj — APPROVED** [review]
Tests are passing:
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  206 passed, 137 warnings in 226.57s (0:03:46) ---
--- PYTEST UNIT TESTS PASSED  118 passed, 241 warnings in 967.97s (0:16:07) ---
--- PYTEST VET TESTS FAILED  1 failed, 32 passed, 10 warnings in 854.20s (0:14:14) ---
--- PYPEIT DEVELOPMENT SUITE FAILED 1/168 TESTS  ---
Failed tests:
    mmt_mmirs/HK_zJ pypeit
Skipped tests:
Testing Started at 2023-03-06T19:46:15.830216
Testing Completed at 2023-03-07T04:26:30.447328
Total Time: 8:40:14.617112

**Comment by profxj** [comment]
Running the DevSuite one more time..

**Comment by profxj** [comment]
3 test failures that I think are unrelated to this PR:

Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  206 passed, 136 warnings in 194.75s (0:03:14) ---
--- PYTEST UNIT TESTS PASSED  118 passed, 240 warnings in 874.06s (0:14:34) ---
--- PYTEST VET TESTS PASSED  33 passed, 9 warnings in 759.38s (0:12:39) ---
--- PYPEIT DEVELOPMENT SUITE FAILED 3/169 TESTS  ---
Failed tests:
    mmt_mmirs/HK_zJ pypeit
    gemini_gmos/GN_E2V_MULTI_R400_600 pypeit
    gemini_gmos/GS_HAM_MULTI_R400_700 pypeit
Skipped tests:
Testing Started at 2023-03-10T13:50:21.899295
Testing Completed at 2023-03-10T21:53:31.379237
Total Time: 8:03:09.479942

**Pull request merged**
