### PR TITLE
Hotfix for FITS file with extra padding bytes at the end

### PR DESCRIPTION
**Pull request by finagle29**
If there are extra trailing bytes after the data section of a FITS HDU, astropy.fits.open treats that as a new broken HDU and errors out, crashing PypeIt. Setting ignore_missing_end=True to all raw (i.e. not produced by PypeIt) FITS file reads ignores missing END cards in the header, and fixes this problem. See astropy/astropy#4351 for further discussion of the problem.

I ran across this bug with some DBSP data, not sure if other supported instruments also produced this type malformed FITS files.

### CODE REVIEW

**Comment by profxj** [comment]
Thanks for this @finagle29 --
am wondering if we should generalize by having a (very simple)
`read_raw_fits()` method in `pypeit.io.py` so that we wouldn't have
to touch all the occurrences.

Of course, you already have so if you prefer not to bother that is ok too.
and, if you did, this would make you touch them all again.. 

Your call.  I am approving any which way.

**Review by profxj — APPROVED** [review]
approved

**Review by kbwestfall — APPROVED** [review]
I'm approving, but I agree with @profxj about having a centralized method in `pypeit.io`.  Something like:

```
def fits_open(filename):
    try:
        return fits.open(filename)
    except OSError as e:
        msgs.warn('Error opening {0}: {1}'.format(filename, str(e)) + '\nTrying again, assuming the error was a header problem.')
        return fits.open(filename, ignore_missing_end=True)
```

Maybe a bit onerous, but it centralizes the issue into a single method and alerts the user that their files have this issue.  I leave it up to you.

**Comment by finagle29** [comment]
Good idea, I'll make something like pypeit.io.fits_open

**Comment by profxj** [comment]
@finagle29 -- Should probably run all tests given this touched 
so many key files.  I can do so on my end if you prefer.  Just
let me know.  Thanks.

**Comment by finagle29** [comment]
@profxj that would be great, thanks!

**Comment by profxj** [comment]
Tests started

**Comment by profxj** [comment]
--- PYPEIT DEVELOPMENT SUITE FAILED 1/89 TESTS (Masters ignored) ---
Only NIRES; ignoring

Unit tests passed too.

**Pull request merged**
