### PR TITLE
Refactor PyQt5 -> PySide2

### PR DESCRIPTION
**Pull request by finagle29**
PySide2 has a more permissive license (LGPL 3) than PyQt5 (GPL 3), and practically the same public API.

Companion to linetools/linetools#523

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Approved

**Review by deborape — APPROVED** [review]
Approved!

**Comment by profxj** [comment]
@finagle29 -- merge with linetools when ready.

**Comment by finagle29** [comment]
merging!

**Pull request merged**
