### PR TITLE
Fix using Polynomial Telluric model for high-flux objects

### PR DESCRIPTION
**Pull request by finagle29**
The `max_scale` of `1e5` set in `poly_telluric` was not being propagated through to `core.coadd.solve_poly_ratio`.  This caused high flux objects (like standard stars) to be completely masked when using a polynomial object model because the initial ratio found by `robust_median_ratio` would max out at 10, resulting in a bad initial fit, and all data points being masked before the differential evolution. This presented (to me at least) as a `numpy` `ValueError: output array is read-only`.

```
    TelPoly = telluric.poly_telluric(args['spec1dfile'], par['tellfit']['tell_grid'], modelfile, outfile,
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/pypeit/core/telluric.py", line 1590, in poly_telluric
    TelObj = Telluric(wave, flux, ivar, mask_tot, telgridfile, obj_params,
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/pypeit/core/telluric.py", line 1875, in __init__
    obj_dict, bounds_obj = init_obj_model(obj_params, iord,
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/pypeit/core/telluric.py", line 1001, in init_poly_model
    scale, fit_tuple, flux_scale, ivar_scale, outmask = coadd.solve_poly_ratio(
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/pypeit/core/coadd.py", line 575, in solve_poly_ratio
    result, ymodel, ivartot, outmask = utils.robust_optimize(flux_ref, poly_ratio_fitfunc, arg_dict, inmask=mask_ref,
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/pypeit/utils.py", line 1011, in robust_optimize
    ret_tuple = fitfunc(ydata, thismask, arg_dict, **kwargs_optimizer)
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/pypeit/core/coadd.py", line 423, in poly_ratio_fitfunc
    result = scipy.optimize.minimize(poly_ratio_fitfunc_chi2, guess, args=(flux_ref, thismask, arg_dict),  **kwargs_opt)
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/pypeit/core/coadd.py", line 368, in poly_ratio_fitfunc_chi2
    chi_mean, chi_median, chi_std = stats.sigma_clipped_stats(
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/astropy/stats/sigma_clipping.py", line 756, in sigma_clipped_stats
    mean = np.nanmean(data_clipped, axis=axis)
  File "<__array_function__ internals>", line 5, in nanmean
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 950, in nanmean
    avg = _divide_by_count(tot, cnt, out=out)
  File "/home/mroberso/mroberso/anaconda3/envs/dbsp_drp_dev/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 212, in _divide_by_count
    return np.divide(a, b, out=a, casting='unsafe')
ValueError: output array is read-only
```

### CODE REVIEW

**Comment by finagle29** [comment]
Unit tests passing
``================ 246 passed, 680 warnings in 958.58s (0:15:58) =================``

**Review by jhennawi — APPROVED** [review]
Thanks for these bug fixes!

**Review by feigewang — APPROVED** [review]
Thanks for fixing this.

**Comment by profxj** [comment]
merging

**Pull request merged**
