### PR TITLE
Add reid_arxiv template for MMTO's Binospec and the x270 grating

### PR DESCRIPTION
**Pull request by tepickering**
As the title says, this PR adds:

- Script for creating `reid_arxiv` templates for Binospec. We may or may not need to add coverage for the `x270` grating. Templates for the other gratings are a work in progress.
- The `reid_arxiv` file, currently based on a solution determined with central wavelength set to 6500 A.
- Modify `mmt_binospec.py` to use this `reid_arxiv` solution when the `x270` disperser is used.
- Tests initially failed due to change in the format of `tox.ini`. Fix for that included here.

### CODE REVIEW

**Review by feigewang — COMMENTED** [review]
Thanks @tepickering for adding the wavelength solution. One minor comment, maybe we should add the central wavelength info for the archived template in the file name.

**Comment by tepickering** [comment]
the central wavelength is included in the wave calibration file in https://github.com/pypeit/PypeIt-development-suite/pull/233. if we add solutions from different central wavelengths, those files go there in the Dev Suite and then `pypeit/core/wavecal/spectrographs/templ_mmt_binospec.py` needs to be modified to combine them into the single template in `reid_arxiv`. `templ_ldt_deveny.py` has examples of how that is done.

**Comment by feigewang** [comment]
> 

Okay. Thanks for the explanation. I will go ahead to approve it.

**Review by feigewang — APPROVED** [review]
Thanks!

**Review by kbwestfall — APPROVED** [review]
Looks good!  Is there are relevant dataset in the dev-suite that this should be run on?  I see the `Mulitslit_G270` dataset; does that use the `x270` grating?

**Comment by profxj** [comment]
(pypeit) profx> tail westfall-binoreid-16dec22.report 

Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  195 passed, 10 skipped, 709 warnings in 225.46s (0:03:45) ---
--- PYTEST UNIT TESTS PASSED  118 passed, 1239 warnings in 952.41s (0:15:52) ---
--- PYTEST VET TESTS PASSED  28 passed, 980 warnings in 822.96s (0:13:42) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 155/155 TESTS  ---
Testing Started at 2022-12-16T18:35:03.070209
Testing Completed at 2022-12-17T04:27:09.185330
Total Time: 9:52:06.115121

**Pull request merged**
