### PR TITLE
Add verbosity option to post-processing scripts

### PR DESCRIPTION
**Pull request by tbowers7**
The default verbosity level for `run_pypeit` is 2 (with an option to change it), but the other scripts have a default verbosity = 1 with no means to change it from the command line.  Given that several scripts do heavy post-processing (coadding, flux calibrating, etc.), debugging of user issues can be more challenging without the higher verbosity level (and logging).

This change adds the `--verbosity N` option to various post-processing scripts. In addition to being able to change the verbosity, when set to Level 2 a log file is also produced.  The log filename includes the name of the script and a timestamp (to the minute) for reference in the event of multiple runs of the script.

### CODE REVIEW

**Comment by tbowers7** [comment]
PypeIt and Dev-Suite Unit Tests all pass:
```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  201 passed, 1275 warnings in 222.59s (0:03:42) ---
--- PYTEST UNIT TESTS PASSED  115 passed, 1894 warnings in 1235.41s (0:20:35) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 0/0 TESTS  ---
Testing Started at 2022-09-15T15:16:58.155493
Testing Completed at 2022-09-15T15:41:19.021832
Total Time: 0:24:20.866339
```
Full `dev-suite` not run because no processing code touched.

**Review by profxj — APPROVED** [review]
Looks great!

Please confirm the `script` unit tests are passing in the DevSuite.

**Review by kbwestfall — CHANGES_REQUESTED** [review]
Thanks @tbowers7, and sorry I didn't ask this earlier:  Can you instead make the `set_verbosity_and_logfile` method part of the `Messages` class?

**Comment by tbowers7** [comment]
> Looks great!
> 
> Please confirm the `script` unit tests are passing in the DevSuite.

@profxj: Is there something other than `./pypeit_test pypeit_tests unit` I should be running in the DevSuite to ensure I get all the `script` tests?

**Review by kbwestfall — APPROVED** [review]
Thanks!

**Comment by tbowers7** [comment]
```
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  201 passed, 1258 warnings in 230.40s (0:03:50) ---
--- PYTEST UNIT TESTS PASSED  115 passed, 1886 warnings in 1243.00s (0:20:42) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 0/0 TESTS  ---
Testing Started at 2022-09-26T12:40:05.445196
Testing Completed at 2022-09-26T13:04:41.697849
Total Time: 0:24:36.252653
```
I'll ask for a full `dev-suite` run w/ VET tests, since some of the scripts are tested there.

**Comment by tbowers7** [comment]
All tests pass, including all scripts.
```
Test Summary 
-------------------------------------------------------- 
--- PYTEST PYPEIT UNIT TESTS PASSED  201 passed, 1181 warnings in 246.29s (0:04:06) --- 
--- PYTEST UNIT TESTS PASSED  118 passed, 1793 warnings in 1228.27s (0:20:28) --- 
--- PYTEST VET TESTS PASSED  25 passed, 1565 warnings in 1014.09s (0:16:54) --- 
--- PYPEIT DEVELOPMENT SUITE PASSED 153/153 TESTS --- 
Testing Started at 2022-09-27T12:40:23.457224 
Testing Completed at 2022-09-28T00:03:53.052510 
Total Time: 11:23:29.595286 
```

**Pull request merged**
