### PR TITLE
spec1d txt file HOTFIX

### PR DESCRIPTION
**Pull request by debora-pe**
In some of the recent changes, two lines of the code have been commented, de facto undoing the changes added by PR #1154 
This PR fixes it.

To be absolutely sure, I have re-run the Dev Suite.

```
--- PYPEIT DEVELOPMENT SUITE PASSED 108/108 TESTS (Masters ignored) ---
Testing Started at 2021-04-24T16:38:27.322268
Testing Completed at 2021-04-24T20:38:07.416435
Total Time: 3:59:40.094167
```

### CODE REVIEW

**Review by profxj — APPROVED** [review]
hope it wasn't me..  ;)

**Review by jhennawi — APPROVED** [review]
It says you are out of date with develop. If these are significant changes you will need to test again.

**Comment by debora-pe** [comment]
Somehow it was out of date with develop for some changes in the docs. Nothing significant.
These are the files that changes:
```
Fast-forward
 CHANGES.rst                              |   7 ++++++-
 doc/help/pypeit_chk_for_calibs.rst       |  33 +++++++++++++++++----------------
 doc/help/pypeit_coadd_2dspec.rst         |  15 +++++++++++----
 doc/help/pypeit_collate_1d.rst           |  35 +++++++++++++++++++++++------------
 doc/help/pypeit_obslog.rst               |  32 ++++++++++++++++----------------
 doc/help/pypeit_ql_keck_mosfire.rst      |  29 +++++++++++++++++++++--------
 doc/help/pypeit_sensfunc.rst             |  11 ++++++++---
 doc/help/pypeit_setup.rst                |  33 +++++++++++++++++----------------
 doc/help/pypeit_show_2dspec.rst          |   4 +++-
 doc/help/pypeit_tellfit.rst              |  23 ++++++++++++-----------
 doc/help/pypeit_trace_edges.rst          |  10 +++++-----
 doc/help/pypeit_view_fits.rst            |  27 ++++++++++++++++-----------
 doc/help/run_pypeit.rst                  |  25 +++++++++++++------------
 doc/include/datamodel_specobj.rst        | 124 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------------------------------------------------------
 doc/include/shane_kast_blue_A.pypeit.rst |   2 +-
 doc/include/spectrographs_table.rst      |  85 +++++++++++++++++++++++++++++++++++++++++++------------------------------------------
 doc/pypeit_par.rst                       | 160 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------------------------------------------
 doc/scripts/build_specobj_rst.py         |   7 ++++++-
 pypeit/spectrographs/vlt_xshooter.py     |   7 ++++---
 19 files changed, 366 insertions(+), 303 deletions(-)
```

**Comment by debora-pe** [comment]
I'm merging

**Pull request merged**
