### PR TITLE
Vacuum hotfix

### PR DESCRIPTION
**Pull request by profxj**
Modify docs and parameter list to indicate we are in vacuum only in PypeIt.

### CODE REVIEW

**Review by rcooke-ast — APPROVED** [review]
Good riddance, air...

**Review by kbwestfall — APPROVED** [review]
Nice.  I like it.  I would also specify that the wavelengths are in vacuum in as screaming bold text as you can muster in the descriptions of the main output products (spec1d, spec2d, etc).

**Review by deborape — COMMENTED** [review]
In `pypeitpar.py`, Should you remove `medium` also in lines 2068 and 2325?

**Comment by profxj** [comment]
Good catch @deborape .

Removed.

**Pull request merged**
