### PR TITLE
wavecal for 600/7500

### PR DESCRIPTION
**Pull request by rcooke-ast**
This PR adds support for Shane/KASTr 600/7500 grating... Holy Grail worked so well for so long...

image

### CODE REVIEW

**Review by kbwestfall — APPROVED** [review]
Looks good to me.  Can you post the results from running the dev-suite on the relevant `shane_kast_red` setups?

**Comment by rcooke-ast** [comment]
Sure thing - Here are the results:
image

**Review by profxj — APPROVED** [review]
Thanks thanks.

Can you confirm that the wavelength `vet` test 
is still passing before merging?

https://github.com/pypeit/PypeIt-development-suite/blob/develop/vet_tests/test_wavelengths.py#L18

**Comment by rcooke-ast** [comment]
Here is the output of the command:
` python -m pytest test_wavelengths.py -k test_shane_kast_red`
The relevant kast test passes.

image

**Pull request merged**
