### PR TITLE
Coadd1d hotfix

### PR DESCRIPTION
**Pull request by debora-pe**
This allows coadd1d to be run if only one spec1d is provided.

### CODE REVIEW

**Review by kbwestfall — APPROVED** [review]
Quick and easy!

Is there anything that should be changed in the docs that indicate this?  I.e., how do we tell the user what happens when there's only one spectrum.

Also, add something in the change log.

**Comment by debora-pe** [comment]
> Quick and easy!
> 
> Is there anything that should be changed in the docs that indicate this? I.e., how do we tell the user what happens when there's only one spectrum.
> 
> Also, add something in the change log.

@kbwestfall Added to the change log.
This is fixing a bug that was introduced recently, therefore the documentation is currently (after we fix this) correct.

**Comment by freddavies** [comment]
Looks good to me!

**Review by freddavies — APPROVED** [review]

**Comment by debora-pe** [comment]
merging

**Pull request merged**
