### PR TITLE
update MK extinction data

### PR DESCRIPTION
**Pull request by rcooke-ast**
Update for Mauna Kea extinction data: [Buton et al. 2013](https://ui.adsabs.harvard.edu/abs/2013A%26A...549A...8B/abstract)

### CODE REVIEW

**Review by jhennawi — CHANGES_REQUESTED** [review]
Thanks for updating this @rcooke-ast. Can you add a note to the header about telluric lines are being treated here. In other words, are they being interpolated over (which is what I gather) from inspecting the numbers. 

Thanks!

**Comment by rcooke-ast** [comment]
Thanks @jhennawi - A skim read suggests they have a high resolution telluric spectrum, and convolve this with a Gaussian to a resolution of R~1000. So, telluric absorption is included, but at a somewhat low resolution. Seems reasonable to me...

**Review by feigewang — COMMENTED** [review]
Thanks @rcooke-ast for updating this. Could you please add one comment in the header to describe the uncertainty of the extinction curve. It seems to be 0.001-0.04 mag from 0.3-1.0 um by looking at their table.

**Review by jhennawi — APPROVED** [review]
Thanks @rcooke-ast!

**Comment by rcooke-ast** [comment]
Thanks @feigewang - good idea - I've included this now.

**Review by feigewang — APPROVED** [review]
Thanks

**Pull request merged**
