### PR TITLE
Dark Current updated for all spectrographs

### PR DESCRIPTION
**Pull request by rcooke-ast**
For many spectrographs, the dark current was defined as e-/s/pixel, but the DetectorContainer Data Model in PypeIt actually requires e-/hour/pixel. Therefore, there are multiple spectrographs that have had their base variance underestimated.

### CODE REVIEW

**Review by kbwestfall — CHANGES_REQUESTED** [review]
Thanks for digging in on this!  My only request is that we perform the multiplications.  I.e., instead of setting the value to, e.g., `0.5*3600.`, I'd rather we put in `1800.`.

**Review by debora-pe — APPROVED** [review]
Looks good to me. Thank you for doing this.
Please, run the tests.

**Review by kbwestfall — APPROVED** [review]
Approving!

**Comment by rcooke-ast** [comment]
Updated format, and made all units clear. Running dev suite now...

**Comment by rcooke-ast** [comment]
Dev suite passes... merging...
image

**Pull request merged**
