### PR TITLE
Shane Red 1200/5000 reid file updated

### PR DESCRIPTION
**Pull request by profxj**
This PR extends the archived wavelength solution for the shane_kast_red 1200/5000 grating

The currently archived one is tiltled blueward of the DevSuite spectrum.

This PR splines the two.  There is will be a companion 
DevSuite PR shortly.

Here is the QA on the DevSuite for wavelengths:

Arc_1dfit_A_0_DET01_S0293

### CODE REVIEW

**Review by rcooke-ast — APPROVED** [review]
Approved (FYI, it was easier for me to fix a typo, than comment for you to fix it)!

**Review by kbwestfall — APPROVED** [review]
Thanks!  I can confirm this fixes the error I was getting with the combination of python 3.12 and scipy 1.12.0.

**Review by rcooke-ast — COMMENTED** [review]
Maybe just update the changes doc?

**Comment by profxj** [comment]
(pypeit) namor> ./pypeit_test -t 8 -i shane_kast_red reduce
usage: pypeit_test [-h] [-o OUTPUTDIR] [-i INSTRUMENTS [INSTRUMENTS ...]]
                   [-s SETUPS [SETUPS ...]] [--debug] [-p] [-m] [-t THREADS]
                   [-q] [-v] [--coverage COVERAGE] [-r REPORT] [-c CSV] [-w]
                   tests [tests ...]
pypeit_test: error: the following arguments are required: tests
(pypeit) namor> ./pypeit_test -i shane_kast_red -t 8 reduce
Running reduce tests.
Running tests on the following instruments:
    shane_kast_red

Reducing data from shane_kast_red for the following setups:
    300_7500_Ne
    600_7500_d55_ret
    600_7500_d57
    600_5000_d46
    1200_5000_d57

Running tests in 8 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_7500_d57 pypeit
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_5000_d46 pypeit
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/1200_5000_d57 pypeit
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/300_7500_Ne pypeit
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_7500_d55_ret pypeit
 1 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_7500_d55_ret pypeit
 2 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/300_7500_Ne pypeit
 3 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/1200_5000_d57 pypeit
 4 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_5000_d46 pypeit
 5 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_7500_d57 pypeit
--- PYPEIT DEVELOPMENT SUITE PASSED 5/5 TESTS  ---

Test Summary
--------------------------------------------------------
--- PYPEIT DEVELOPMENT SUITE PASSED 5/5 TESTS  ---
Testing Started at 2024-03-21T15:53:23.917638
Testing Completed at 2024-03-21T16:11:16.985473
Total Time: 0:17:53.067835

**Comment by profxj** [comment]
(pypeit) namor> py.test test_wavelengths.py::test_shane_kast_red
============================= test session starts =============================
platform linux -- Python 3.10.12, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/xavier/Projects/PypeIt-Codes/PypeIt-development-suite/vet_tests
plugins: filter-subpackage-0.1.2, mock-3.11.1, anyio-3.7.1, astropy-header-0.2.2, openfiles-0.5.0, arraydiff-0.5.0, ligo.skymap-1.1.1, cov-4.1.0, doctestplus-0.13.0, astropy-0.10.0, asdf-3.0.0, remotedata-0.4.0, hypothesis-6.82.0
collected 1 item                                                              

test_wavelengths.py .                                                   [100%]

============================== 1 passed in 1.10s ==============================

**Comment by profxj** [comment]
merging

**Pull request merged**
