### PR TITLE
Remove Travis CI configuration

### PR DESCRIPTION
**Pull request by tepickering**
Now that #1081 is merged and GitHub Actions enabled for CI, there is no longer any need to use a 3rd party solution. The PR removes the Travis CI configuration and completes the transition to GitHub Actions. It also includes a small fix from astropy/astropy#11054 to avoid two sets of Actions test runs being run when a PR is opened.

### CODE REVIEW

**Review by profxj — APPROVED** [review]

**Review by kbwestfall — APPROVED** [review]

**Comment by profxj** [comment]
Nice!

Can you move the Travis file to `pypeit/deprecated` ?
Instead of deleting.

You know, just in case.  ;)

**Comment by profxj** [comment]
I'll merge afterwards.  Thanks

**Comment by tepickering** [comment]
the file still exists in the git history and can always be retrieved that way. i guess stashing it in `pypeit/deprecated` is more readily human-readable, though, so i'll revert and move.

**Comment by profxj** [comment]
merging.  Goodbye Travis

**Pull request merged**
