### PR TITLE
Deal with empty subtbl hotfix

### PR DESCRIPTION
**Pull request by profxj**
Am pretty sure this hotfix should go to `develop`
but please confirm @kbwestfall

### CODE REVIEW

**Review by kbwestfall — APPROVED** [review]
Nice!

**Comment by profxj** [comment]
@kbwestfall -- Can you jump on this branch and remake it 
so that the `-c` option of `pypeit_setup` restricts the number
of pypeit files written?  I fear it was turned off.  

Let's not merge this until it is back.  Thanks!

**Comment by kbwestfall** [comment]
Sorry, big oversight on my part.  I fixed the issue.  For a quick test, try:

```
pypeit_setup -r "RAW_DATA/keck_deimos/830G_L_8?00/" -s keck_deimos -c A
```

in the dev-suite.  I ran the tests before (merging with `develop`) and they all passed.

**Review by rcooke-ast — APPROVED** [review]
Looks good to me!

**Comment by profxj** [comment]
merging

**Pull request merged**
