### PR TITLE
Add `pixelflat_waveimg` to `MasterFlat` output

### PR DESCRIPTION
**Pull request by tbowers7**
As titled.  Involves a version bump in the `FlatImages` datamodel, but no change to the `minimum_version` because there is no incompatibility with the previous datamodel.

As part of debugging some flat field issues with `LDT/DeVeny`, I found it helpful to use the wavelength image that is generated as part of `FlatField.fit()`.  I have made a slight modification to the `FlatImages` datamodel to include this image in the `MasterFlat` output as one of the HDUs. @profxj suggested I submit this PR for the benefit of the community.

Testing (units / dev-suite) is in progress...

### CODE REVIEW

**Comment by tbowers7** [comment]
The inclusion of `minimum_version` in `pypeit.flatfield.FlatImages()` seemed to
indicate that multiple versions of a data model would be valid, so long as they
lie between `minimim_version` and `version`, inclusive.  Unfortunately, it
appears that this functionality has not yet been implemented.

The version check happens in `pypeit.datamodel.DataContainer._parse()`, and only
includes equality statements.  Additionally, the class attribute
`minimum_version` is not referenced in the `_parse()` method and only appears
in the active code base in the data container classes of `pypeit/alignframe.py`,
`pypeit/flatfield.py`, and `pypeit/slittrace.py`.

This leads to a quandary of how to proceed.  This commit retains the original
data model version `1.1.0`, despite the fact that the model has changed
slightly.  We could update the version number (and update the Cooked data), but
this may cause unnecessary disruption for users upon upgrade.

The final option would be to modify `DataContainer._parse()` to check the data
container version against both the current and minumum versions.  This would
seem like the most correct path forward, but would require extensive testing
and may be outside the scope of this particular PR.

**Review by kbwestfall — APPROVED** [review]
Looks good to me.  Can you comment on the increased size in the `MasterFlat` file for your instrument?

On the datamodel version: yes, the minimum version number is not something we've fully implemented and you can ignore it for now.  I think you *should* change the version number.  This means that people may have to re-reduce their data for use with a new PypeIt release, but that's been par for the course for our new releases.

**Review by jhennawi — CHANGES_REQUESTED** [review]
Dear @tbowers7, 

Thanks for this PR. I agree that adding the waveimg here has some value, even though it is already written to disk. If made part of the data model it is more accessible. 

That said, the main tool for debugging the flats is the pypeit_chk_flats script which lives at scripts/chk_flats.py. Right now it is not using the waveimg. That script calls the show() method in FlatImages in flatfield.py. 

Could you please add the wavelength image to this show method by modifying the call to 

viewer, ch = display.show_image(img, chname=name, cuts=cut, wcs_match=wcs_match,
                                        clear=clear)

on line 1243 to be 

viewer, ch = display.show_image(img, chname=name, cuts=cut, wcs_match=wcs_match, waveimg=pixflat_waveimg, clear=clear)

In that way, the flat QA images will now display with the wavelength indicated in ginga. 

Thanks!

**Comment by tbowers7** [comment]
**Note:** `release` was pulled in to get unit tests to pass.  I can modify the PR, if needed, to remove this merge.

@kbwestfall : For `LDT/DeVeny`, the `MasterFlat` before this change is 24MB, and 32MB including the wave image.

@jhennawi : Thank you for pointing out how to add the wavelength calibration to `pypeit_chk_flats` -- this is much easier to use than loading the separate FITS extensions in my own analysis code.  That being said, I believe this change adds the only full 2D wave image to the Masters files (science 2D spec files have wave images) -- helpful if debugging a set of calibration-only data.

Both: With the change in flatfield data model version to `1.1.1`, should I run up a new `Cooked` set for use with the unit tests?  There may be a conflict with other testing going on.

**Comment by tbowers7** [comment]
Unit test summary:
```
=========================== short test summary info ============================
FAILED pypeit/tests/test_scienceimage.py::test_instantiate_from_one - pypeit....
FAILED pypeit/tests/test_scienceimage.py::test_from_list - pypeit.pypmsgs.Pyp...
FAILED pypeit/tests/test_scripts.py::test_chk_flat - pypeit.pypmsgs.PypeItErr...
========== 3 failed, 304 passed, 4435 warnings in 1865.54s (0:31:05) ===========

__________________________ test_instantiate_from_one ___________________________

[ERROR]   :: datamodel.py 1350 from_hdu() - Current version of FlatImages object 
in code (v1.1.1) does not match version used to write your HDU(s)!

________________________________ test_from_list ________________________________
[ERROR]   :: datamodel.py 1350 from_hdu() - Current version of FlatImages object 
in code (v1.1.1) does not match version used to write your HDU(s)!

________________________________ test_chk_flat _________________________________
[ERROR]   :: datamodel.py 1350 from_hdu() - Current version of FlatImages object 
in code (v1.1.1) does not match version used to write your HDU(s)!
```
Everything passes except the change in datamodel version.

**Comment by kbwestfall** [comment]
Hi @tbowers7.  Yes, based on the test faults, it looks like you need to rebuild the cooked tarfile.  In the top-level dev-suite directory, this should amount to running:

```
./pypeit_test cooked
./build_cooked 1.7.0
```

Then update the relevant Cooked version number in `pypeit/tests/test_cooked.py`.

**Comment by tbowers7** [comment]
@kbwestfall : Thanks, will do.  What branch of the dev-suite should I be using, or does it matter?

**Comment by kbwestfall** [comment]
> @kbwestfall : Thanks, will do. What branch of the dev-suite should I be using, or does it matter?

Work on the `develop` branch.

**Comment by tbowers7** [comment]
Unit tests all pass against new cooked `1.7.0`.
```
============================= test session starts ==============================
collected 307 items                                                            

pypeit/tests/test_alignments.py .                                        [  0%]
pypeit/tests/test_arc.py .                                               [  0%]
pypeit/tests/test_archive.py ..                                          [  1%]
pypeit/tests/test_arcimage.py ..                                         [  1%]
pypeit/tests/test_biasframe.py ..                                        [  2%]
pypeit/tests/test_bitmask.py ....                                        [  3%]
pypeit/tests/test_bpmimage.py ..                                         [  4%]
pypeit/tests/test_bspline.py ...............                             [  9%]
pypeit/tests/test_buildimage.py ..                                       [ 10%]
pypeit/tests/test_calibrations.py .......                                [ 12%]
pypeit/tests/test_chk_calibs.py ..                                       [ 13%]
pypeit/tests/test_coadd.py .                                             [ 13%]
pypeit/tests/test_collate_1d.py ............                             [ 17%]
pypeit/tests/test_cooked.py .                                            [ 17%]
pypeit/tests/test_coremeta.py .                                          [ 17%]
pypeit/tests/test_datacontainer.py ........                              [ 20%]
pypeit/tests/test_detector.py ...                                        [ 21%]
pypeit/tests/test_display.py .                                           [ 21%]
pypeit/tests/test_edgetrace.py .                                         [ 22%]
pypeit/tests/test_fitting.py ....                                        [ 23%]
pypeit/tests/test_flatfield.py .                                         [ 23%]
pypeit/tests/test_flexure.py ..                                          [ 24%]
pypeit/tests/test_flux.py ....                                           [ 25%]
pypeit/tests/test_fluxspec.py .....                                      [ 27%]
pypeit/tests/test_frametype.py ..                                        [ 28%]
pypeit/tests/test_history.py ....                                        [ 29%]
pypeit/tests/test_load.py .                                              [ 29%]
pypeit/tests/test_load_images.py ................                        [ 34%]
pypeit/tests/test_manual.py ..                                           [ 35%]
pypeit/tests/test_maskdesign_matching.py ...                             [ 36%]
pypeit/tests/test_masterframe.py .                                       [ 36%]
pypeit/tests/test_match.py ....                                          [ 38%]
pypeit/tests/test_metadata.py ......                                     [ 40%]
pypeit/tests/test_moment.py ......                                       [ 42%]
pypeit/tests/test_msgs.py ..                                             [ 42%]
pypeit/tests/test_opticalmodel.py ....                                   [ 43%]
pypeit/tests/test_parse.py ...                                           [ 44%]
pypeit/tests/test_pca.py ........                                        [ 47%]
pypeit/tests/test_processimage.py ..                                     [ 48%]
pypeit/tests/test_procimg.py .....                                       [ 49%]
pypeit/tests/test_pydl.py .                                              [ 50%]
pypeit/tests/test_pypeit.py ..                                           [ 50%]
pypeit/tests/test_pypeitimage.py ..                                      [ 51%]
pypeit/tests/test_pypeitpar.py ...............................           [ 61%]
pypeit/tests/test_pypeitsetup.py ........                                [ 64%]
pypeit/tests/test_qa.py .                                                [ 64%]
pypeit/tests/test_runpypeit.py ..                                        [ 65%]
pypeit/tests/test_scienceimage.py ...                                    [ 66%]
pypeit/tests/test_scripts.py ..................                          [ 71%]
pypeit/tests/test_setups.py ......................                       [ 79%]
pypeit/tests/test_skysub.py ..                                           [ 79%]
pypeit/tests/test_slitmask.py ...                                        [ 80%]
pypeit/tests/test_slittrace.py ....                                      [ 82%]
pypeit/tests/test_spec2dobj.py ......                                    [ 84%]
pypeit/tests/test_specobj.py .......                                     [ 86%]
pypeit/tests/test_specobjs.py .....                                      [ 87%]
pypeit/tests/test_spectrographs.py ....................                  [ 94%]
pypeit/tests/test_syncspec.py .                                          [ 94%]
pypeit/tests/test_telluric.py ..                                         [ 95%]
pypeit/tests/test_traceimage.py .                                        [ 95%]
pypeit/tests/test_utils.py ....                                          [ 97%]
pypeit/tests/test_vcorr.py ..                                            [ 97%]
pypeit/tests/test_wavemodel.py .                                         [ 98%]
pypeit/tests/test_wavetilts.py ....                                      [ 99%]
pypeit/tests/test_wvcalib.py ..                                          [100%]

=============== 307 passed, 4438 warnings in 1795.02s (0:29:55) ================
```

`dev-suite` run is in progress.

**Comment by tbowers7** [comment]
`dev-suite` run on branch `develop` (with the latest `RAW_DATA` files copied in from the Google Drive) complete.  There were two failed tests, but I am at a loss for why.  The `vlt_xshooter` failure seems related to the recent manual extraction changes, but the `mmt_binospec` run just ended during the flat fielding without errors, but still signaling failure.
```
--- PYPEIT DEVELOPMENT SUITE FAILED 2/135 TESTS (Masters ignored) ---
Failed tests:
    vlt_xshooter/VIS_manual pypeit (without masters)
    mmt_binospec/Longslit_G600 pypeit (without masters)
Skipped tests:
    vlt_xshooter/VIS_manual pypeit_coadd_2dspec
Testing Started at 2022-01-11T14:59:01.171350
Testing Completed at 2022-01-12T04:39:02.969372
Total Time: 13:40:01.798022

--- End of log output for vlt_xshooter/VIS_manual pypeit (without masters) :
...
[INFO]    :: procimg.py 171 lacosmic() - Growing cosmic ray mask by 1 pixel
[INFO]    :: reduce.py 165 __init__() - Initialising slits
[INFO]    :: reduce.py 332 run_objfind() - Generating tilts image
[INFO]    :: extract.py 1968 ech_objfind() - Finding objects on order # 30
Traceback (most recent call last):
  File "/home/tbowers/miniconda3/envs/pypeit/bin/run_pypeit", line 33, in <module>
    sys.exit(load_entry_point('pypeit', 'console_scripts', 'run_pypeit')())
  File "/home/tbowers/d1/codes/PypeIt/pypeit/scripts/scriptbase.py", line 110, in entry_point
    cls.main(cls.parse_args())
  File "/home/tbowers/d1/codes/PypeIt/pypeit/scripts/run_pypeit.py", line 142, in main
    pypeIt.reduce_all()
  File "/home/tbowers/d1/codes/PypeIt/pypeit/pypeit.py", line 422, in reduce_all
    sci_spec2d, sci_sobjs = self.reduce_exposure(frames, bg_frames=bg_frames,
  File "/home/tbowers/d1/codes/PypeIt/pypeit/pypeit.py", line 579, in reduce_exposure
    global_sky, sobjs_obj, skymask, sciImg = self.objfind_one(
  File "/home/tbowers/d1/codes/PypeIt/pypeit/pypeit.py", line 834, in objfind_one
    global_sky, sobjs_obj, skymask = self.redux.run_objfind(std_trace=std_trace, show_peaks=self.show)
  File "/home/tbowers/d1/codes/PypeIt/pypeit/reduce.py", line 341, in run_objfind
    self.find_objects(self.sciImg.image, std_trace=std_trace,
  File "/home/tbowers/d1/codes/PypeIt/pypeit/reduce.py", line 553, in find_objects
    self.find_objects_pypeline(image,
  File "/home/tbowers/d1/codes/PypeIt/pypeit/reduce.py", line 1350, in find_objects_pypeline
    sobjs_ech, skymask[self.slitmask > -1] = extract.ech_objfind(
  File "/home/tbowers/d1/codes/PypeIt/pypeit/core/extract.py", line 1983, in ech_objfind
    for ss, spat, spec, f_spat in zip(range(len(hand_extract_dict['hand_extract_spec'])),
KeyError: 'hand_extract_spec'


--- End of log output for mmt_binospec/Longslit_G600 pypeit (without masters):
...
[INFO]    :: flatfield.py 977 fit() - Performing 2D illumination + scattered light flat field fit
[INFO]    :: fitting.py 1101 bspline_profile() - B-spline fit:
[INFO]    :: fitting.py 1102 bspline_profile() -     npoly = 7 profile basis functions
[INFO]    :: fitting.py 1103 bspline_profile() -     ngood = 10052549/10055184 measurements
[INFO]    :: fitting.py 1104 bspline_profile() - ***************** Iter     Chi^2    N Rej  R. Fac *****************
[INFO]    :: fitting.py 1108 bspline_profile() -                   ----  --------  -------  ------                  
[INFO]    :: fitting.py 1202 bspline_profile() -                      1     1.505    29659    1.00                  
[INFO]    :: fitting.py 1202 bspline_profile() -                      2     1.364    31638    1.00                  

[Note: Log just ends; no errors reported.]
```

**Comment by kbwestfall** [comment]
Hi @tbowers7 .  Don't worry about the `VIS_manual` failure.  @deborape and I also found this and will have fixed it in other branches before yours gets merged.  For the `mmt_binospec/Longslit_G600` test, can you try running only that test again?  You should be able to do that by running: `./pypeit_test mmt_binospec -s Longslit_G600` or `./pypeit_test develop -i mmt_binospec -s Longslit_G600`.  I'm not sure why it should just stop executing.

**Comment by tbowers7** [comment]
Hi @kbwestfall .  Run by itself, after deleting all relevant `REDUX_OUT` files from the previous run, it was happy.
```
(pypeit) tbowers@Zephyr:/data/tbowers/PypeIt-development-suite$ rm -rf REDUX_OUT/mmt_binospec/Longslit_G600/
(pypeit) tbowers@Zephyr:/data/tbowers/PypeIt-development-suite$ ./pypeit_test develop -i mmt_binospec -s Longslit_G600
Running tests on the following instruments:
    mmt_binospec

Reducing data from mmt_binospec for the following setups:
    Longslit_G600

 0 passed/ 0 failed/ 0 skipped STARTED mmt_binospec/Longslit_G600 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  mmt_binospec/Longslit_G600 pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 1/1 TESTS (Masters ignored) ---
Testing Started at 2022-01-12T16:48:34.837230
Testing Completed at 2022-01-12T17:51:40.096086
Total Time: 1:03:05.258856
```
Why it wasn't happy before, with a completely deleted `REDUX_OUT`, I can't say.

**Comment by jhennawi** [comment]
Thanks @tbowers7, good point about the waveimg not being written to masters. I'm approving since it looks like tests passed.

**Review by jhennawi — APPROVED** [review]
Thanks for this!

**Comment by tbowers7** [comment]
Hi @kbwestfall : I think I have tracked down the `mmt_binospec` `dev-suite` failure to "Impatient User" Error.  I was running more simultaneous processes than I really had RAM for, and I think the crash was a memory issue.  I re-ran the `dev-suite` using the proper number of processes for my RAM, and now only have the aforementioned `VIS_manual` error.
```
--- PYPEIT DEVELOPMENT SUITE FAILED 1/135 TESTS (Masters ignored) ---
Failed tests:
    vlt_xshooter/VIS_manual pypeit (without masters)
Skipped tests:
    vlt_xshooter/VIS_manual pypeit_coadd_2dspec
Testing Started at 2022-01-13T16:46:01.963047
Testing Completed at 2022-01-14T13:34:03.278010
Total Time: 20:48:01.314963
```

**Comment by profxj** [comment]
@tbowers7 -- please pull in `develop` and then merge.
  Thx!

**Comment by tbowers7** [comment]
@profxj : `develop` pulled in.  I don't have write access, but this PR is ready for someone on the team to merge.

Thanks!

**Pull request merged**
