### PR TITLE
Keck HIRES / LRIS updates from ADAP work

### PR DESCRIPTION
**Pull request by badpandabear**
Some updates made to improve keck_hires support:

- Support flats and darks
- Detect slitless flats
- Deal with empty MJD values in the header
- Add ``decker`` and ``dispname`` to the keck_hires configuration keys
- Update floating point comparisons when comparing configurations to support a 0 echangle
- Fix handling of setup names with two characters (e.g. 'AA') in PypeItMetaData
- Minimize annoying `The instrument name in the headers of the raw files does not match the` warnings from when the name in the headers starts with the instrument name

Plus a bonus LRIS change to detect direct imaging/non-spectroscopic frames.

### CODE REVIEW

**Comment by badpandabear** [comment]
Requires dev-suite PR https://github.com/pypeit/PypeIt-development-suite/pull/318

**Comment by badpandabear** [comment]
First run of devsuite

```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  249 passed, 65 warnings in 578.95s (0:09:38) ---
--- PYTEST UNIT TESTS FAILED  3 failed, 131 passed, 168 warnings in 1046.63s (0:17:26) ---
--- PYTEST VET TESTS PASSED  61 passed, 97 warnings in 6188.16s (1:43:08) ---
--- PYPEIT DEVELOPMENT SUITE FAILED 2/237 TESTS  ---
Failed tests:
    keck_nirspec/LOW_NIRSPEC-1 pypeit
    keck_hires/J0100+2802_N255Hr_RED_C2_ECH_0.74_XD_1.39_1x3 pypeit
Skipped tests:
Testing Started at 2024-04-22T20:53:46.595769
Testing Completed at 2024-04-23T18:54:26.584653
Total Time: 22:00:39.988884
```
Second run
```
Running reduce tests.
Running afterburner tests
Running quick look tests
Running tests on the following instruments:
    keck_hires

Reducing data from keck_hires for the following setups:
    J0100+2802_N255Hr_RED_C2_ECH_0.74_XD_1.39_1x3

 0 passed/ 0 failed/ 0 skipped STARTED keck_hires/J0100+2802_N255Hr_RED_C2_ECH_0.74_XD_1.39_1x3 pypeit
 1 passed/ 0 failed/ 0 skipped PASSED  keck_hires/J0100+2802_N255Hr_RED_C2_ECH_0.74_XD_1.39_1x3 pypeit
--- PYPEIT DEVELOPMENT SUITE PASSED 1/1 TESTS  ---

Test Summary
--------------------------------------------------------
--- PYPEIT DEVELOPMENT SUITE PASSED 1/1 TESTS  ---
Testing Started at 2024-04-24T12:08:42.270200
Testing Completed at 2024-04-24T12:35:14.113291
Total Time: 0:26:31.843091
```

The remaining problems are nirspec related issues I believe will be fixed with the upcomming nirspec PR.

**Review by kbwestfall — APPROVED** [review]
All looks good to me.

**Review by debora-pe — APPROVED** [review]
Thanks @badpandabear

**Pull request merged**
