### PR TITLE
Refactor ProcessImages

### PR DESCRIPTION
**Pull request by profxj**
As titled, this deprecates `ProcessImages` and replaces it
with several, easier to use objects.  Along the way, this cleans
up part of the mess known as `ScienceImage` and `Reduce`
although there is a lot more work to be done there.

Here are the specific CHANGES:

- Refactor ProcessImages into ProcessImage, PypeItImage and CombinedImage
- More precisely name the load() methods
- Fix arc tilts bug
- Modest refactoring of ScienceImage
- Moved several mask methods to procimg.py

### CODE REVIEW

**Comment by profxj** [comment]
Unit tests passing.  Moving on to Dev suite:

**Comment by profxj** [comment]
(base) profx> py.test --disable-warnings 
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: /data/Projects/Python/PypeIt, inifile:
plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.3.0, arraydiff-0.3
collected 167 items                                                            

pypeit/tests/test_arc.py .                                               [  0%]
pypeit/tests/test_biasframe.py ....                                      [  2%]
pypeit/tests/test_bpmimage.py ...                                        [  4%]
pypeit/tests/test_calibrations.py ..........                             [ 10%]
pypeit/tests/test_coadd.py ...........                                   [ 17%]
pypeit/tests/test_combinedimage.py .                                     [ 17%]
pypeit/tests/test_cooked.py .                                            [ 18%]
pypeit/tests/test_flatfield.py .                                         [ 19%]
pypeit/tests/test_flexure.py .                                           [ 19%]
pypeit/tests/test_flux.py ....                                           [ 22%]
pypeit/tests/test_fluxspec.py ...                                        [ 23%]
pypeit/tests/test_load.py ..                                             [ 25%]
pypeit/tests/test_load_images.py ..........                              [ 31%]
pypeit/tests/test_masterframe.py .                                       [ 31%]
pypeit/tests/test_match.py ....                                          [ 34%]
pypeit/tests/test_metadata.py .....                                      [ 37%]
pypeit/tests/test_msgs.py ..                                             [ 38%]
pypeit/tests/test_opticalmodel.py ....                                   [ 40%]
pypeit/tests/test_parse.py ...                                           [ 42%]
pypeit/tests/test_processimage.py ...                                    [ 44%]
pypeit/tests/test_procimg.py .                                           [ 44%]
pypeit/tests/test_pydl.py .                                              [ 45%]
pypeit/tests/test_pypeit.py ..                                           [ 46%]
pypeit/tests/test_pypeitimage.py ..                                      [ 47%]
pypeit/tests/test_pypeitpar.py ......................                    [ 61%]
pypeit/tests/test_pypeitsetup.py .......                                 [ 65%]
pypeit/tests/test_qa.py .                                                [ 65%]
pypeit/tests/test_save.py ..                                             [ 67%]
pypeit/tests/test_scripts.py ......                                      [ 70%]
pypeit/tests/test_setups.py ..............                               [ 79%]
pypeit/tests/test_slitmask.py .                                          [ 79%]
pypeit/tests/test_specobj.py ..                                          [ 80%]
pypeit/tests/test_specobjs.py ....                                       [ 83%]
pypeit/tests/test_spectrographs.py ............                          [ 90%]
pypeit/tests/test_traceimage.py ..                                       [ 91%]
pypeit/tests/test_traceslits.py .....                                    [ 94%]
pypeit/tests/test_utils.py ..                                            [ 95%]
pypeit/tests/test_vcorr.py ..                                            [ 97%]
pypeit/tests/test_wavecalib.py .                                         [ 97%]
pypeit/tests/test_waveimage.py .                                         [ 98%]
pypeit/tests/test_wavemodel.py .                                         [ 98%]
pypeit/tests/test_wavetilts.py ..                                        [100%]

================== 167 passed, 135 warnings in 685.44 seconds ==================

**Comment by profxj** [comment]
I think the Dev Suite is now passing provided one is on the
`mosfire` branch.  But it would be good for @jhennawi to 
run overnight as it is hard for me to do so in Hawaii.

Just fixed VLT 2x2.

**Comment by jhennawi** [comment]
This PR needs to be to develop, not to master as per the usual rules of engagement. Please resubmit and I'll start reviewing it.

**Pull request closed without merging**
