### PR TITLE
set method for SpecObjs

### PR DESCRIPTION
**Pull request by profxj**
Responding to #451 

The syntax that @jhennawi requested in that Issue is not
achievable given the way we are over-loading ```__getitem___```.
So I have constructed a ```set()``` method instead.  Only klunky
part is that one has to insert a ```slice``` object if you want to slice, e.g.

sobjs.set(slice(1,2), 'det', 2)

Includes new tests and updated Notebook.

### CODE REVIEW

**Comment by profxj** [comment]
ps. see the updated Notebook:

https://github.com/pypeit/PypeIt/blob/specobjs/doc/nb/SpecObjs.ipynb

**Comment by jhennawi** [comment]
I'm not understanding why you can't similarly overload __setitem__ @profxj. 

Take a look at how the astropy.table does it starting on line 1220 of the following code:

https://github.com/astropy/astropy/blob/master/astropy/table/table.py

They manage to overload both __getitem__ and __setitem__. I modeled the changes to our __getitem__ to enable slicing etc. based on their example. What is the difference that is preventing us from similarly following their lead on __setitem__?

**Comment by profxj** [comment]
Hmm..  I had convinced myself it wasn't possible because
of the way we were slicing the ```SpecObjs``` object but as
I wake up today I am reconsidering.  Let me see what I can do.

**Comment by profxj** [comment]
I think I got it @jhennawi 

Time for you to do a Review.

**Comment by jhennawi** [comment]
HI @profxj take a look at the __getitem__ right above where you wrote the __setitem__. I think you need to write some conditional along those lines in order to deal with all the usage cases. For example that __getitem__ takes your slicing example as a special case, but it also can handle an numpy array of booleans which your implementation won't handle. 

In other words, given what you have coded up this below will fail: 

indx = (sobjs['spat_pixpos'] > YYY)
sobjs[indx]['spat_pixpos'] = XXX

I got around this by simply casting to an numpy array of objects. 
Joe

**Comment by profxj** [comment]
Have you tried this test @jhennawi ?

If not, you should before you raise it as a problem.

**Comment by jhennawi** [comment]
I've merged these changes with my own changes to specobjs in the extract_sep18 branch. The merge was tricky, but done so let's get these changes in via that extract_sep18 branch. Thus I'm closing this request.

**Pull request closed without merging**
