### PR TITLE
Hotfix: Platescale binning correction

### PR DESCRIPTION
**Pull request by tbowers7**
In `pypeit.find_objects.MultiSlitFindObjects.get_platescale()`, the platescale is scaled by the binning -- but the code accidentally was using the *spectral* binning rather than the *spatial* binning.  This value is used to compute the BOXCAR RADIUS in the `pypeit.core.findobj_skymask.objs_in_slit()` function, which is then saved in the `SpecObj` object.

This PR corrects the binning scaling to use the SPATIAL binning.

	modified:   pypeit/find_objects.py

### CODE REVIEW

**Review by kbwestfall — APPROVED** [review]
Looks good to me!  I think we should run tests, unless we're confident that this isn't going to cause any object detection issues in the dev-suite.

**Review by debora-pe — APPROVED** [review]
Great catch @tbowers7!

**Comment by kbwestfall** [comment]
Hi @tbowers7 .  I got one dev-suite failure:

```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  240 passed, 70 warnings in 556.04s (0:09:16) ---
--- PYTEST UNIT TESTS PASSED  133 passed, 171 warnings in 1027.10s (0:17:07) ---
--- PYTEST VET TESTS PASSED  58 passed, 69 warnings in 2245.07s (0:37:25) ---
--- PYPEIT DEVELOPMENT SUITE FAILED 1/233 TESTS  ---
Failed tests:
    ldt_deveny/DV7 pypeit
Skipped tests:
Testing Started at 2023-11-07T16:52:09.355981
Testing Completed at 2023-11-08T08:42:18.270379
Total Time: 15:50:08.914398
```

Here's the log entry:
```
-------------------------
Test Setup: ldt_deveny/DV7

-------------------------
Directories:
         Raw data: /tmp/PypeIt-development-suite/RAW_DATA/ldt_deveny/DV7
    PypeIt output: /tmp/REDUX_OUT/ldt_deveny/DV7
Files:
     .pypeit file: None
 Std .pypeit file: None
Tests:
----
ldt_deveny/DV7 pypeit Result: [1;31m--- FAILED[0m

Logfile:    /tmp/REDUX_OUT/ldt_deveny/DV7/ldt_deveny_dv7.test.log
Process Id: 1308
Start time: Wed Nov  8 06:04:26 2023
End time:   Wed Nov  8 06:04:41 2023
Duration:   0:00:14.484929
Mem Usage:  621867008
Command:    run_pypeit /tmp/REDUX_OUT/ldt_deveny/DV7/ldt_deveny_dv7.pypeit -o

Error Messages:

End of Log:
             Use the script `pypeit_install_linelist` to install
             your custom line list into the cache.  See instructions at
             https://pypeit.readthedocs.io/en/latest/wave_calib.html#line-lists
```

I'm not sure what caused the error.  Can you look into this?

**Comment by tbowers7** [comment]
> I'm not sure what caused the error. Can you look into this?

@kbwestfall : This is fixed in #1712.

**Comment by kbwestfall** [comment]
> > I'm not sure what caused the error. Can you look into this?
> 
> @kbwestfall : This is fixed in #1712.

Okay, great!  Will merge soon.

**Pull request merged**
