### PR TITLE
Reduce edge thresh for Magellan FIRE Echelle

### PR DESCRIPTION
**Pull request by profxj**
As titled

### CODE REVIEW

**Comment by profxj** [comment]
See PypeIt Users Slack for discussion

**Comment by profxj** [comment]
(base) profx> ./pypeit_test -i magellan_fire -t 4 develop
Running tests on the following instruments:
    magellan_fire

Reducing data from magellan_fire for the following setups:
    FIRE_Echelle
    FIRE_Long

Running tests in 4 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED magellan_fire/FIRE_Echelle pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED magellan_fire/FIRE_Long pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  magellan_fire/FIRE_Long pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  magellan_fire/FIRE_Echelle pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 2/2 TESTS (Masters ignored) ---
Testing Started at 2022-05-04T06:54:44.097149
Testing Completed at 2022-05-04T08:24:33.221007
Total Time: 1:29:49.123858

**Comment by profxj** [comment]
@feigewang reports that lowering from 10 may have negative
consequences..

**Review by jhennawi — APPROVED** [review]
Can you post a screenshot from pypeit_chk_edges?

**Review by feigewang — APPROVED** [review]
Thanks

**Pull request merged**
