### PR TITLE
chk_wavecalib script

### PR DESCRIPTION
**Pull request by profxj**
Simple script to print diagnostics of WaveCalib to the terminal.

And a 'speed up' option for `pypeit_show_2dspec`

### CODE REVIEW

**Comment by profxj** [comment]
=============== 254 passed, 408 warnings in 1132.06s (0:18:52) ================

**Review by kbwestfall — APPROVED** [review]
Looks good!

**Review by astronomeara — APPROVED** [review]

**Review by jhennawi — COMMENTED** [review]
Can you indicate which channels are which in the documentation.

**Comment by deborape** [comment]
@profxj sorry for missing this. Thank you for this work!

**Pull request merged**
