### PR TITLE
Various updates for NOT ALFOSC

### PR DESCRIPTION
**Pull request by Raindogjones**
Adds support for all commonly used grisms as well as adding the handful of missing recommended standards.

### CODE REVIEW

**Review by rcooke-ast — APPROVED** [review]
All seems good to me - thanks for the contribution! I'm sure all is fine, but I don't suppose you have saved some of the QA to demonstrate the quality of the wavelength calibration (or, perhaps you can confirm that the `rms_tol` for all of the setups added are within some value)?

**Review by profxj — APPROVED** [review]
Am approving, but before we merge, can we add all of these new
grisms to the DevSuite?

I can share a Drive folder with you @Raindogjones

**Comment by rcooke-ast** [comment]
I'll also add one more comment... please update the `CHANGES.rst` file, to mention that you've added support for these new grisms  :-)

**Comment by Raindogjones** [comment]
> All seems good to me - thanks for the contribution! I'm sure all is fine, but I don't suppose you have saved some of the QA to demonstrate the quality of the wavelength calibration (or, perhaps you can confirm that the `rms_tol` for all of the setups added are within some value)?

All the grisms are within the normal 0.1 rmstol except grisms 10 and 11 for which I needed to bump that up to 0.2
Those grisms are usually only used as cross-dispersers for an echelle, but there have been something like 2 programmes in the last ten years which have used them to do spectro-photometry because they are the lowest resolution we offer. So, I don't think the slightly poorer wavelength calibration will ever be a problem, I just wanted to mention it in the readme, just in case.

**Comment by Raindogjones** [comment]
> Am approving, but before we merge, can we add all of these new grisms to the DevSuite?
> 
> I can share a Drive folder with you @Raindogjones

Sure, @profxj, please share the not_alfosc folder with me and I'll dump some data on there.

**Comment by profxj** [comment]
Thx!  Kindly remind me of your email.
 And also upload the PypeIt files too

  And I can generate a then PR to the DevSuite if you wish

**Comment by profxj** [comment]
Actually, I think I just gave you editor access @Raindogjones 

https://drive.google.com/drive/folders/1fVGQ8wad8fCFsPUjtI0F1YiKUh4fNgD5?usp=sharing

**Comment by Raindogjones** [comment]
@profxj Running the tests now to make sure everything is in order, then I'll submit the PR to the dev-suite.

**Comment by Raindogjones** [comment]
Looks good!
 0 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism3 pypeit 
 1 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism3 pypeit 
 1 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism5 pypeit 
 2 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism5 pypeit 
 2 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism17 pypeit 
 3 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism17 pypeit 
 3 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism20 pypeit 
 4 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism20 pypeit 
 4 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism19 pypeit 
 5 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism19 pypeit 
 5 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism11 pypeit 
 6 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism11 pypeit 
 6 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism18 pypeit 
 7 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism18 pypeit 
 7 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism10 pypeit 
 8 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism10 pypeit 
 8 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism4 pypeit 
 9 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism4 pypeit 
 9 passed/ 0 failed/ 0 skipped STARTED not_alfosc/grism7 pypeit 
10 passed/ 0 failed/ 0 skipped PASSED  not_alfosc/grism7 pypeit 
--- PYPEIT DEVELOPMENT SUITE PASSED 10/10 TESTS  ---

**Pull request merged**
