### PR TITLE
Tracing bug fix + develop & doc update

### PR DESCRIPTION
**Pull request by kbwestfall**
This PR:
 - addresses #1066 (see the change in `pypeit/core/trace.py`),
 - updates the `develop` branch for hot-fixes in `master`, and 
 - updates the docs.

### CODE REVIEW

**Comment by kbwestfall** [comment]
Tests pass: ```=== 252 passed in 1109.34s (0:18:29) ===```

**Review by profxj — APPROVED** [review]
Approved

**Review by deborape — APPROVED** [review]
Looks good!

**Comment by profxj** [comment]
merging

**Pull request merged**
