### PR TITLE
Improved wavelength solution for Gemini-N R400 on the E2V chip

### PR DESCRIPTION
**Pull request by profxj**
As titled.

This is paired with https://github.com/pypeit/PypeIt-development-suite/pull/198

which implements tests on Gemini masks.

Here is one of the nice wavelength solutions (the high RMS is
due to the over-sampling):

Arc_1dfit_A_1_MSC01_S1511

### CODE REVIEW

**Comment by profxj** [comment]
Will post tests on the weekend, but 
things look fine on my laptop.

**Comment by profxj** [comment]
Addresses https://github.com/pypeit/PypeIt/issues/1383

**Review by kbwestfall — APPROVED** [review]
Looks good.  Just be sure, will the new default approach work if (for some reason) someone wants to reduce individual detectors instead of the mosaic?

**Review by debora-pe — APPROVED** [review]
Looks good! 
One thing: You could use `par['calibrations']['wavelengths']['fwhm_fromlines'] = True` if you like. It will compute the fwhm using the arc lines.

**Comment by profxj** [comment]
=============== 329 passed, 4253 warnings in 1746.11s (0:29:06) ================

**Comment by profxj** [comment]
=============== 329 passed, 4253 warnings in 1725.83s (0:28:45) ================

**Comment by profxj** [comment]
Running the full DevSuite given my bug fixes..

**Comment by profxj** [comment]
Failing only the usual OBJ nonsense:

--- PYPEIT DEVELOPMENT SUITE FAILED 1/139 TESTS (Masters ignored) ---

**Pull request merged**
