### PR TITLE
HOTFIX: skysub gui

### PR DESCRIPTION
**Pull request by rcooke-ast**
Addresses Issue #1479

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Am assuming this was tested. :)

**Comment by rcooke-ast** [comment]
Yes, tested... but only on matplotlib 3.5... (not 3.6) - the solution implemented is the common approach used as described online  🤞

**Review by kbwestfall — APPROVED** [review]
Thanks for addressing the issue!  I'm approving and happy for you to merge, but two thoughts:
- Should this go to `release` instead of `develop`?  Maybe it's not worth it because it likely means you'd have to redo the edits in a new branch that branches from `release` instead of `develop` (to avoid including all the other edits already in `develop`).
- I recently had to manipulate the `keymap` items in `rcParams`.  Is there any reason not to turn them all off?  I did:
```
for key in plt.rcParams.keys():
    if 'keymap' in key:
        plt.rcParams[key] = []
```
Also, I'm not sure it matters, but you might want to also add `plt.rcdefaults()` at the end to make sure the defaults are restored.

**Comment by rcooke-ast** [comment]
Good points @kbwestfall - I have added a call to `finalize` that resets to the matplotlib defaults. I've also used your code to unset all keymaps, and then just initialise the ones that matter to me

I don't think this script is used all that often, so pushing to release is probably not critical, but I'm happy to cherry pick this commit there - shouldn't be any other conflicts. There's also a workaround that users can specify `user_regions`, which is less "clicky" but still available...

**Pull request merged**
