### PR TITLE
Shane Kast Red fixes

### PR DESCRIPTION
**Pull request by profxj**
As titled, this fixes two bugs encountered by Elleanor Gates:

1. The archived 300/7500 wavelength solution was windowed.  Now fixes (for Ne case)
2. Apparently some users window off Amp 1.  This caused a crash, now fixed.

### CODE REVIEW

**Comment by profxj** [comment]
Passing Dev suite, and I confirmed the 300/7500 wavelengths
for the windowed detector are fine.

(base) profx> ./pypeit_test -t 5 -i shane_kast_red develop
Running tests on the following instruments:
    shane_kast_red

Reducing data from shane_kast_red for the following setups:
    300_7500_Ne
    600_7500_d55_ret
    600_7500_d57
    600_5000_d46
    1200_5000_d57

Running tests in 5 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_7500_d57 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/1200_5000_d57 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/300_7500_Ne pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_7500_d55_ret pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_5000_d46 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_5000_d46 pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_7500_d55_ret pypeit (without masters)
 3 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/300_7500_Ne pypeit (without masters)
 4 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/1200_5000_d57 pypeit (without masters)
 5 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_7500_d57 pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 5/5 TESTS (Masters ignored) ---

**Review by jhennawi — APPROVED** [review]
Please run Shane Kast red tests before you merge.

**Comment by profxj** [comment]
Tests are already run and posted.

**Review by kbwestfall — APPROVED** [review]
Looks good!

**Pull request merged**
