### PR TITLE
Merges develop into release (1.12.2 tag)

### PR DESCRIPTION
**Pull request by kbwestfall**
As titled.

Docs updated. Unit tests pass, but I did not rerun the full dev-suite.

New tag has already been pushed.

Anyone can approve and merge.

### CODE REVIEW

**Comment by tbowers7** [comment]
The `develop` branch docs on readthedocs is missing the module API for the new `specutils` loaders.
https://pypeit.readthedocs.io/en/develop/api/pypeit.specutils.pypeit_loaders.html
Can this be fixed before merging?

**Review by profxj — APPROVED** [review]
giddy up

**Review by profxj — APPROVED** [review]
let's do it!

**Comment by kbwestfall** [comment]
> The `develop` branch docs on readthedocs is missing the module API for the new `specutils` loaders. https://pypeit.readthedocs.io/en/develop/api/pypeit.specutils.pypeit_loaders.html Can this be fixed before merging?

Okay, finally got it.  Check this out:

https://pypeit.readthedocs.io/en/staged/api/pypeit.specutils.pypeit_loaders.html#pypeit.specutils.pypeit_loaders.pypeit_spec1d_loader

And then feel free to approve and merge :)

**Review by badpandabear — APPROVED** [review]

**Pull request merged**
