### PR TITLE
Add Wavelength RMS to SpecObj

### PR DESCRIPTION
**Pull request by profxj**
As titled.

This means a (minor) update to the `SpecObj` data model.

In support of #1152 as requested by @marlageha

### CODE REVIEW

**Comment by profxj** [comment]
--- PYPEIT DEVELOPMENT SUITE PASSED 96/96 TESTS (Masters ignored) ---

**Comment by debora-pe** [comment]
@profxj this looks good! 
I was thinking that it would be good to add `WAVE_RMS` to the `spec1d....txt` file for an easy inspection. If you want I can jump into the branch and add it myself.

And I guess there are still CI tests that fail.

**Comment by profxj** [comment]
Added to txt file:

```
(base) profx> m Science/spec1d_b27-J1217p3905_KASTb_2015May20T045733.560.txt 
| slit |                    name | spat_pixpos | spat_fracpos | box_width 
| opt_fwhm |  s2n | wv_rms |
|  175 | SPAT0176-SLIT0175-DET01 |       175.5 |        0.502 |      3.00 
|    2.222 | 9.87 |  0.015 |

```

**Review by marlageha — APPROVED** [review]
Thanks.  This looks good, will be a useful value to have in the spec1d files.

**Review by debora-pe — APPROVED** [review]
@profxj  you may have not pushed yet the changes to the .txt file. I don't see them.

Otherwise, approved.

**Review by jhennawi — APPROVED** [review]
Looks good.

**Pull request merged**
