### PR TITLE
Add FRAMENO to PypeIt files of most Keck instruments

### PR DESCRIPTION
**Pull request by profxj**
As titled

### CODE REVIEW

**Comment by profxj** [comment]
Tests have stalled..

108 passed/ 0 failed/ 0 skipped PASSED  keck_deimos/900ZD_M_6000 pypeit (without masters)

**Review by jhennawi — APPROVED** [review]
Thanks. Full tests should not be needed, but just run the unit tests and check that pypeit_setup and pypeit_obslog look reasonable.

**Review by kbwestfall — APPROVED** [review]
Looks good!

**Comment by profxj** [comment]
|          filename |       frametype |           ra |          dec |         target |       dispname |        decker | binning |            mjd |    airmass |   exptime | filter1 | frameno |  dithpat | dithpos | dithoff | calib | comb_id | bkg_id |
| m191118_0064.fits |         science |  88.12398597 |  15.88291243 |          GD 71 | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58805.44935772 | 1.09461722 |  59.64639 |       Y |      64 |    Stare |  object |     0.0 |     0 |      10 |     -1 |
| m191118_0065.fits |         science |  88.12816249 |  15.88180566 |          GD 71 | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58805.45082161 | 1.09057571 |  59.64639 |       Y |      65 |    Stare |  object |     0.0 |     0 |       4 |     -1 |
| m191119_0027.fits | pixelflat,trace |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18380414 | 1.41291034 |  11.63832 |       Y |      27 |    Stare |  object |     0.0 |     0 |      -1 |     -1 |
| m191119_0028.fits | pixelflat,trace |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18403434 | 1.41291034 |  11.63832 |       Y |      28 |    Stare |  object |     0.0 |     0 |      -1 |     -1 |
| m191119_0029.fits | pixelflat,trace |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18427636 | 1.41291034 |  11.63832 |       Y |      29 |    Stare |  object |     0.0 |     0 |      -1 |     -1 |
| m191119_0030.fits | pixelflat,trace |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18452022 | 1.41291034 |  11.63832 |       Y |      30 |    Stare |  object |     0.0 |     0 |      -1 |     -1 |
| m191119_0031.fits | pixelflat,trace |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18476039 | 1.41291034 |  11.63832 |       Y |      31 |    Stare |  object |     0.0 |     0 |      -1 |     -1 |
| m191119_0037.fits |        standard |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18642497 | 1.41291034 |  11.63832 |       Y |      37 |    Stare |  object |     0.0 |     0 |       8 |     -1 |
| m191119_0038.fits |        standard |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18665518 | 1.41291034 |  11.63832 |       Y |      38 |    Stare |  object |     0.0 |     0 |       9 |     -1 |
| m191119_0039.fits |        standard |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18689719 | 1.41291034 |  11.63832 |       Y |      39 |    Stare |  object |     0.0 |     0 |       3 |     -1 |
| m191119_0040.fits |        standard |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 |  58806.1871333 | 1.41291034 |  11.63832 |       Y |      40 |    Stare |  object |     0.0 |     0 |       7 |     -1 |
| m191119_0041.fits |        standard |        230.0 |         45.0 |      DOME FLAT | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58806.18737532 | 1.41291034 |  11.63832 |       Y |      41 |    Stare |  object |     0.0 |     0 |      11 |     -1 |
| m191120_0043.fits |         science | 323.13191558 | -14.57624247 | J2132-1434_OFF | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58807.25895078 | 1.47652532 | 149.84337 |       Y |      43 | Mask Nod |       A |     7.9 |     0 |       2 |     -1 |
| m191120_0044.fits |         science | 323.13616419 | -14.57470789 | J2132-1434_OFF | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58807.26107578 | 1.49132421 | 149.84337 |       Y |      44 | Mask Nod |       B |    -7.9 |     0 |       6 |     -1 |
| m191120_0045.fits |         science | 323.13191558 | -14.57624247 | J2132-1434_OFF | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58807.26320899 |  1.5069382 | 149.84337 |       Y |      45 | Mask Nod |       A |     7.9 |     0 |       1 |     -1 |
| m191120_0046.fits |         science | 323.13616419 | -14.57470789 | J2132-1434_OFF | Y-spectroscopy | LONGSLIT-46x1 |     1,1 | 58807.26531987 | 1.52273222 | 149.84337 |       Y |      46 | Mask Nod |       B |    -7.9 |     0 |       5 |     -1 |

**Comment by profxj** [comment]
(base) profx> ./pypeit_test -t 10 -i keck_mosfire develop
Running tests on the following instruments:
    keck_mosfire

Reducing data from keck_mosfire for the following setups:
    Y_long
    J_multi
    K_long

Running tests in 10 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED keck_mosfire/J_multi pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED keck_mosfire/Y_long pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED keck_mosfire/K_long pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  keck_mosfire/K_long pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  keck_mosfire/Y_long pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped STARTED keck_mosfire/Y_long pypeit_sensfunc
 3 passed/ 0 failed/ 0 skipped PASSED  keck_mosfire/Y_long pypeit_sensfunc
 3 passed/ 0 failed/ 0 skipped STARTED keck_mosfire/Y_long pypeit_ql
 4 passed/ 0 failed/ 0 skipped PASSED  keck_mosfire/Y_long pypeit_ql
 5 passed/ 0 failed/ 0 skipped PASSED  keck_mosfire/J_multi pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 5/5 TESTS (Masters ignored) ---

**Comment by profxj** [comment]
(base) profx> !2018
./pypeit_test -t 10 -i keck_nires develop
Running tests on the following instruments:
    keck_nires

Reducing data from keck_nires for the following setups:
    NIRES

Running tests in 10 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED keck_nires/NIRES pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  keck_nires/NIRES pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped STARTED keck_nires/NIRES pypeit_ql
 2 passed/ 0 failed/ 0 skipped PASSED  keck_nires/NIRES pypeit_ql

--- PYPEIT DEVELOPMENT SUITE PASSED 2/2 TESTS (Masters ignored) ---

**Pull request merged**
