### PR TITLE
Saving Header information (and some FORS2)

### PR DESCRIPTION
**Pull request by profxj**
This PR starts the effort to relay header informtaion
into the spec1D files produced by PypeIt.  I could go
farther but the COADD codes are getting revamped.

This provides a path for @feigewang and @jhennawi to follow.
Note that it will require us to add a INSTRUME value for each
spectrograph (as in FORS2).

### CODE REVIEW

**Comment by profxj** [comment]
Passing unit tests but will need to generate a new Cooked
before merging.

**Comment by profxj** [comment]
(base) profx> py.test --disable-warnings 
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: /data/Projects/Python/PypeIt, inifile:
plugins: remotedata-0.3.1, openfiles-0.3.2, doctestplus-0.3.0, cov-2.7.1, arraydiff-0.3
collected 165 items                                                            

pypeit/tests/test_arc.py .                                               [  0%]
pypeit/tests/test_biasframe.py ....                                      [  3%]
pypeit/tests/test_bpmimage.py ...                                        [  4%]
pypeit/tests/test_calibrationimage.py .                                  [  5%]
pypeit/tests/test_calibrations.py ..........                             [ 11%]
pypeit/tests/test_coadd.py ...........                                   [ 18%]
pypeit/tests/test_cooked.py .                                            [ 18%]
pypeit/tests/test_flatfield.py .                                         [ 19%]
pypeit/tests/test_flexure.py .                                           [ 20%]
pypeit/tests/test_flux.py ....                                           [ 22%]
pypeit/tests/test_fluxspec.py ...                                        [ 24%]
pypeit/tests/test_load.py ..                                             [ 25%]
pypeit/tests/test_load_images.py ..........                              [ 31%]
pypeit/tests/test_masterframe.py .                                       [ 32%]
pypeit/tests/test_match.py ....                                          [ 34%]
pypeit/tests/test_metadata.py .....                                      [ 37%]
pypeit/tests/test_msgs.py ..                                             [ 38%]
pypeit/tests/test_opticalmodel.py ....                                   [ 41%]
pypeit/tests/test_parse.py ...                                           [ 43%]
pypeit/tests/test_processimage.py ..                                     [ 44%]
pypeit/tests/test_procimg.py .                                           [ 44%]
pypeit/tests/test_pydl.py .                                              [ 45%]
pypeit/tests/test_pypeit.py ..                                           [ 46%]
pypeit/tests/test_pypeitimage.py ..                                      [ 47%]
pypeit/tests/test_pypeitpar.py ......................                    [ 61%]
pypeit/tests/test_pypeitsetup.py .......                                 [ 65%]
pypeit/tests/test_qa.py .                                                [ 66%]
pypeit/tests/test_save.py ..                                             [ 67%]
pypeit/tests/test_scienceimage.py ....                                   [ 69%]
pypeit/tests/test_scripts.py ..                                          [ 70%]
pypeit/tests/test_setups.py .............                                [ 78%]
pypeit/tests/test_slitmask.py .                                          [ 79%]
pypeit/tests/test_specobj.py ..                                          [ 80%]
pypeit/tests/test_specobjs.py ....                                       [ 83%]
pypeit/tests/test_spectrographs.py ............                          [ 90%]
pypeit/tests/test_traceimage.py ..                                       [ 91%]
pypeit/tests/test_traceslits.py .....                                    [ 94%]
pypeit/tests/test_utils.py ..                                            [ 95%]
pypeit/tests/test_vcorr.py ..                                            [ 96%]
pypeit/tests/test_wavecalib.py .                                         [ 97%]
pypeit/tests/test_waveimage.py .                                         [ 98%]
pypeit/tests/test_wavemodel.py .                                         [ 98%]
pypeit/tests/test_wavetilts.py ..                                        [100%]

================== 165 passed, 132 warnings in 606.16 seconds ==================

**Comment by feigewang** [comment]
We wrote a brand new coadd1d code which will replace the coadd.py. The coadd1d code will no longer use the XSpectrum1D. Currently we read all data into an array. I think we need to keep discussing the data model. I will go ahead to approve this PR, but we probably need to copy your changes into our new coadd1d code later.

**Comment by profxj** [comment]
yes, that makes sense.  This is only to get the ball rolling
(and to enable me to generate some spectra that are useful
to a current project).

Thanks

**Comment by feigewang** [comment]
Sounds Good! Please go ahead to merge it in when you finishing generate the new cooked! Thanks!

**Comment by profxj** [comment]
--- PYPEIT DEVELOPMENT SUITE PASSED 27/27 TESTS ---

Building cooked now.

**Pull request merged**
