### PR TITLE
Skysub hotfix

### PR DESCRIPTION
**Pull request by rcooke-ast**
Due to a bug identified on the Users Slack, I've cleaned up the code (significantly reduced!) to make it much easier to maintain.

### CODE REVIEW

**Review by profxj — APPROVED** [review]
All good.

Should we run the DevSuite to make sure removing `scripts/utils.py` is ok?

**Comment by rcooke-ast** [comment]
> Should we run the DevSuite to make sure removing `scripts/utils.py` is ok?

Yes - I'll do that, especially since this is going into release... but I'm pretty sure that I wrote this script a long time ago, and no one ever used it (and it was only used for the skysub regions GUI)!!

Thanks for the review.

**Review by profxj — APPROVED** [review]
thx for the redirect

merge once tests pass

**Comment by rcooke-ast** [comment]
Tests passing...
image

**Review by debora-pe — APPROVED** [review]
Looks good to me!

**Pull request merged**
