### PR TITLE
pypeit_chk_flexure

### PR DESCRIPTION
**Pull request by debora-pe**
As title. New simple script to check the flexure (both spatial and spectral) applied to the science data.

Some examples of how the script works:
```
pypeit_chk_flexure spec1d_DE.20141021.3*.fits --spec
[INFO]    :: Checking fluxure for file: spec1d_DE.20141021.34721-GOODSS_DEIMOS_20141021T093833.706.fits
          NAME          global_spec_shift local_spec_shift total_spec_shift
----------------------- ----------------- ---------------- ----------------
SPAT0038-SLIT0052-MSC01             0.137            0.000            0.137
SPAT0172-SLIT0162-MSC01             0.070            0.000            0.070
SPAT0231-SLIT0224-MSC01             0.073            0.000            0.073
(...)

[INFO]    :: Checking fluxure for file: spec1d_DE.20141021.35719-GOODSS_DEIMOS_20141021T095514.045.fits
          NAME          global_spec_shift local_spec_shift total_spec_shift
----------------------- ----------------- ---------------- ----------------
SPAT0162-SLIT0162-MSC01             0.032            0.000            0.032
SPAT0221-SLIT0224-MSC01             0.037            0.000            0.037
SPAT0249-SLIT0265-MSC01             0.151            0.000            0.151
(...)
```

```
pypeit_chk_flexure spec2d_DE.20141021.34721-GOODSS_DEIMOS_20141021T093833.706.fits --spec
[INFO]    :: Checking fluxure for file: spec2d_DE.20141021.34721-GOODSS_DEIMOS_20141021T093833.706.fits

================================================== MSC01 ================================================
spat_id global_spec_shift
------- -----------------
     52             0.137
    103             0.000
    162             0.070
(...)

================================================== MSC02 ================================================
spat_id global_spec_shift
------- -----------------
     25             0.102
     70             0.075
    210             0.130
(...)
```

```
 pypeit_chk_flexure spec2d_DE.20141021.34721-GOODSS_DEIMOS_20141021T093833.706.fits --spat
[INFO]    :: Checking fluxure for file: spec2d_DE.20141021.34721-GOODSS_DEIMOS_20141021T093833.706.fits

================================================== MSC01 ================================================
Spat shift: None

================================================== MSC02 ================================================
Spat shift: None

================================================== MSC03 ================================================
Spat shift: None

================================================== MSC04 ================================================
Spat shift: None
```

### CODE REVIEW

**Review by kbwestfall — CHANGES_REQUESTED** [review]
Looks good!  Three requests/questions:

 - Add a comment in the release doc
 - Can we use `msgs.info` instead of `print`?
 - Is it necessary to collect and return the tables from all the input files?

**Comment by debora-pe** [comment]
> Looks good! Three requests/questions:
> 
> * Add a comment in the release doc
> * Can we use `msgs.info` instead of `print`?
> * Is it necessary to collect and return the tables from all the input files?

-Thanks @kbwestfall for the reminder to add to the release doc (I always forget!)
-I changed one `print` to `msgs.info` for one information message, but in general, I prefer to leave print, since it not a really a PypeIt message, it's just printing something. And also, most of them are table, so I think they look better.
- Well, yes, I am envisioning using the script to make checks for the ADAP data and returning the table will help with that.

**Review by badpandabear — APPROVED** [review]

**Comment by debora-pe** [comment]
@kbwestfall I followed your suggestion to move the flexure checking code to a function that is then called by `pypeit_chk_flexure`. Let me know what you think.

**Review by kbwestfall — APPROVED** [review]
Thanks for these updates!

**Comment by debora-pe** [comment]
Thanks @badpandabear and @kbwestfall for the quick reviews. I'm merging now.

**Pull request merged**
