### PR TITLE
PYDL license

### PR DESCRIPTION
**Pull request by profxj**
Properly crediting PYDL contributions.

Have also moved the PypeIt license to 
the licenses/ folder.   We should probably
reflect on whether we want the GNU license.
But not as part of this PR.

### CODE REVIEW

**Comment by kbwestfall** [comment]
I'm not sure this is how we should do this.  Interested to know if you were advised to do this.  A few things:

 - I think we need to switch to a BSD-3 license.  The GNU license requires all derived packages to also use the GNU license, and I think we want to avoid that.
 - There are likely some things that @jhennawi directly copied over from pydl, but I think he's also made substantial changes to some of those algorithms.  In both cases, I think we actually just copy the license into the header of the docstring for the module (i.e., the docstring at the top of the file), instead of including the license in a different directory.  For code that @jhennawi has changed substantially, in the docstring for each method, we should say something like "Originally from blah copyright Ben Weaver" and then provide a brief summary of changes.  We just need to follow the rules of Ben's BSD-3 license.
 - I don't think we want the code to have multiple licenses because that will make it confusing for people on what they're allowed to do with the code.  I'd rather we just have one license in the top directory.

**Comment by profxj** [comment]
1. Agreed about BSD-3 for PypeIt.
2. Yes, I was advised (pushed) to do this 
and it has been 'approved' although I agree
with your point about adding items to the doc strings.
3. As for multiple licenses, I'm not sure what you mean.  here is what `astropy` does:

**Comment by kbwestfall** [comment]
I think PypeIt itself should have one license that lives in the top directory.  That, at least, matches with astropy's convention.

The license directory in astropy seems a bit extreme.  It does make sense to collect the licenses of things that we have included in PypeIt (so I guess I take back the comment about the pydl license), but I don't think we need to include licenses for things that we use but don't distribute with the code.  I.e., astropy includes a python license but they don't distribute python source code with astropy (at least I don't think they do).  Specific to PypeIt, I don't think we need to include the numpy license just because we use numpy; we should only have to include it if we distribute numpy code with PypeIt, which we don't.

**Comment by profxj** [comment]
ok, am moving our license back up.  And maybe I should make it BSD-3 now.
Can you point me to one I can 'copy' @kbwestfall ?  Thanks.

**Comment by kbwestfall** [comment]
Yep, here's one: https://opensource.org/licenses/BSD-3-Clause

**Comment by kbwestfall** [comment]
I think I've made changes for the PypeIt versions of both, but we could also add:

https://github.com/sdss/mangadap/blob/master/LICENSE.md

for `ParSet` and `BitMask`, but I'm not too fussed.

**Comment by profxj** [comment]
merging.

**Pull request merged**
