### PR TITLE
KCWI hotfix

### PR DESCRIPTION
**Pull request by rcooke-ast**
This PR is a hotfix for IFU reduction to make sure the sky model is saved. Tests pass...

image

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Looks fine to me.

Can you run tests on one other instrument?  e.g. LRIS?

**Comment by rcooke-ast** [comment]
A few LRIS tests pass:

image

image

**Review by debora-pe — APPROVED** [review]
Looks good to me too.
The CI tests that were not successful seem to be related to a bug that was fix in `release` but not in `develop`. You may need to merge in `release`.

**Comment by rcooke-ast** [comment]
You were right @deborape - and tests still pass... Thanks!!  Merging...
image

**Pull request merged**
