### PR TITLE
Misc stuff (mostly NIRES)

### PR DESCRIPTION
**Pull request by debora-pe**
- added `MASKDEF_OBJMAG`, `MASKDEF_OBJMAG_BAND` in specobj datamodel
- improved NIRES frame typing
- improved NIRES automatic assigning of `comb_id` and `bkg_id` (also added ABC dither pattern)
- improved NIRES doc
- first attempt to get rid of `spectrograph.parse_dither_pattern()` (see changes in pypeit.py). Dither pattern is saved in the `fitstbl` for MOSFIRE, NIRES, GNIRS, so `parse_dither_pattern()` is not necessary. However, `vlt_fors` is computing the dither information in `parse_dither_pattern()` in a somewhat complicated way, so I need some help to translate that into a meta value for the `fitstbl`.

Companion Dev Suite PR: https://github.com/pypeit/PypeIt-development-suite/pull/250
Running the tests.

### CODE REVIEW

**Review by profxj — CHANGES_REQUESTED** [review]
Great stuff!

Can you add a test that runs `pypeit_setup` on the `ERIS` files
and tests that the output is correct?

**Review by kbwestfall — APPROVED** [review]
This all looks good to me.  I had a quick look at the dev suite PR, as well.  Can we add some tests that check the dither pattern logic for the datasets we currently have?

**Comment by debora-pe** [comment]
> This all looks good to me. I had a quick look at the dev suite PR, as well. Can we add some tests that check the dither pattern logic for the datasets we currently have?

Hi @kbwestfall 
We already have a test `test_setup_keck_nires_comb()` in `unit_tests/test_setups.py` that tests the dither pattern. I was  planning to update it, though.

**Comment by debora-pe** [comment]
@kbwestfall , @profxj I have updated the unit test for these changes and added  more datasets in the Dev Suite (also added a coadd2d test). see: https://github.com/pypeit/PypeIt-development-suite/pull/250

@profxj note that I have changed the name of the NIRES datasets, e.g., `ERIS`-->`ABBA_nostandard` 

Also note that I have made a change here in how the S2N for the extracted spec1d is computed, and now it uses only unmasked pixels. see: https://github.com/pypeit/PypeIt/pull/1568/files#diff-f882c79e44684783d3b3247dcf90a693972753500fbe3abe931bcf9ac8816b24R347-R348


I'm re-runnig the tests now.

**Comment by debora-pe** [comment]
Tests pass:

```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  210 passed, 143 warnings in 169.86s (0:02:49) ---
--- PYTEST UNIT TESTS PASSED  118 passed, 248 warnings in 1477.30s (0:24:37) ---
--- PYTEST VET TESTS PASSED  41 passed, 9 warnings in 845.51s (0:14:05) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 179/179 TESTS  ---
Testing Started at 2023-03-28T13:38:24.234653
Testing Completed at 2023-03-28T21:45:08.890098
Total Time: 8:06:44.655445
```

**Review by profxj — APPROVED** [review]
all good

**Pull request merged**
