### PR TITLE
Update GTC OSIRIS find_min_max

### PR DESCRIPTION
**Pull request by Raindogjones**
Traces for low-res grisms don't span the full CCD, so find_min_max should be set

### CODE REVIEW

**Review by rcooke-ast — APPROVED** [review]
Looks good to me!

**Review by jhennawi — APPROVED** [review]
Thanks for this @Raindogjones. It all looks good to me. The full dev-suite should not be required for this PR to clear, but someone should run the GTC OSIRIS tests in the dev-suite at the very least. @Raindogjones are you in a position to run those dev-suite tests. If not, reach out and we can find someone to run them for you.

**Comment by jhennawi** [comment]
Please run the dev-suite tests of only GTC-OSIRIS setups before merging.

**Comment by rcooke-ast** [comment]
There are no R300 or R500 tests in the dev suite, so this PR won't impact those. I'm happy for this to clear and be merged.

**Pull request merged**
