### PR TITLE
Holy fix

### PR DESCRIPTION
**Pull request by profxj**
Add new hooks for Holy Grail, specifically for the
`shane_kast_red` and `shane_kast_red_ret` spectrographs.

Passing tests for those instruments.
Full DevSuite is underway.

### CODE REVIEW

**Comment by profxj** [comment]
`shane_kast_red` only:

./pypeit_test -i shane_kast_red -t 8 develop
Running tests on the following instruments:
    shane_kast_red

Reducing data from shane_kast_red for the following setups:
    300_7500_Ne
    600_7500_d55_ret
    600_7500_d57
    600_5000_d46
    1200_5000_d57

Running tests in 8 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_7500_d57 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/1200_5000_d57 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/300_7500_Ne pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_7500_d55_ret pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED shane_kast_red/600_5000_d46 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_7500_d55_ret pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/300_7500_Ne pypeit (without masters)
 3 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/1200_5000_d57 pypeit (without masters)
 4 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_5000_d46 pypeit (without masters)
 5 passed/ 0 failed/ 0 skipped PASSED  shane_kast_red/600_7500_d57 pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 5/5 TESTS (Masters ignored) ---
Testing Started at 2021-08-10T12:21:51.993794
Testing Completed at 2021-08-10T12:27:38.573593
Total Time: 0:05:46.579799

**Comment by profxj** [comment]
Unit tests:

=============== 287 passed, 4503 warnings in 1410.78s (0:23:30) ================

**Comment by profxj** [comment]
One test failed, will explore/fix it later:

--- PYPEIT DEVELOPMENT SUITE FAILED 1/124 TESTS (Masters ignored) ---
Failed tests:
    keck_deimos/900ZD_M_6000 pypeit (without masters)

**Review by jhennawi — APPROVED** [review]

**Review by kbwestfall — APPROVED** [review]
Approving, but do we understand the DEIMOS failure?

**Comment by profxj** [comment]
Working on it.  Won't merge until it is fixed

**Comment by profxj** [comment]
Have inspected wavelength solutions for LRIS and DEIMOS
to be sure the `ArI` lines weren't hurting them.  They look ok.

And the `keck_deimos/900ZD_M_6000` test passed on my workstation.
Ghosts in the machine...

**Pull request merged**
