### PR TITLE
Maskdef bug

### PR DESCRIPTION
**Pull request by debora-pe**
When PypeIt tries to find the detected object that matches the target object provided by the slitmask design, if more than one object is within a defined tolerance, PypeIt chooses the brightest object. This is not always true and can lead to mismatch (I just found one). This PR change this to have PypeIt choose the object with the smallest separation to the expected position.

I'll run the tests.

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Looks good to me thanks!

**Comment by profxj** [comment]
Do we have anything in the DevSuite testing this by chance?

**Review by kbwestfall — APPROVED** [review]
Looks good!

**Comment by profxj** [comment]
@deborape -- merge when you are happy with this

**Comment by debora-pe** [comment]
I just run a few tests to make sure everything is still good.

Unit tests pass:
`=========== 329 passed in 1439.12s (0:23:59) =============`

Dev Suite for Keck/DEIMOS and Keck/MOSFIRE:

```
Running tests on the following instruments:
    keck_deimos

Reducing data from keck_deimos for the following setups:
    600ZD_M_6500
    600ZD_tilted
    1200G_M_7750
    830G_LVM_8400
    830G_M_8100_26
    830G_M_8500
    830G_L_8100
    1200B_M_5200
    1200G_M_5500
    900ZD_M_6000
    1200B_LVM_5200
    900ZD_LVM_5500
    830G_M_9000_dither
    QL
--- PYPEIT DEVELOPMENT SUITE PASSED 19/19 TESTS (Masters ignored) ---
Testing Started at 2022-04-29T07:59:41.743956
Testing Completed at 2022-04-29T10:54:27.795229
Total Time: 2:54:46.051273
```

```
Running tests on the following instruments:
    keck_mosfire

Reducing data from keck_mosfire for the following setups:
    Y_long
    J_multi
    K_long
    Y_multi
    long2pos1_H
    longslit_3x0.7_H
    mask1_K_with_continuum
    mask1_J_with_continuum

--- PYPEIT DEVELOPMENT SUITE PASSED 10/10 TESTS (Masters ignored) ---
Testing Started at 2022-04-29T10:05:36.824185
Testing Completed at 2022-04-29T10:43:57.163061
Total Time: 0:38:20.338876
```

**Comment by debora-pe** [comment]
I'm merging it.

**Pull request merged**
