### PR TITLE
Hotfix to remove a sort command causing pypeit_setup failures

### PR DESCRIPTION
**Pull request by profxj**
Introduced by JFH

### CODE REVIEW

**Comment by profxj** [comment]
Would you like a filename sort, @jhennawi ?

**Comment by profxj** [comment]
A bogus number?  So the code crashes elsewhere?
Or that number is entirely misused?

None makes far more sense.

**Comment by jhennawi** [comment]
This sounds like the same argument I had about NaNs being left in, which I lost. Anyway, the pypeit file needs to be sorted by MJD. You can fix this bad header bug however you want, but do not comment out that line of code, because I will not tolerate or approve pypeit files that are not sorted by MJD. The easiest way here would be to give a negative MJD or a zero MJD, or something that won't make future operations crash. I also find it hard to believe that you have .fits files for which you cannot pull out a sensible date.

**Comment by jhennawi** [comment]
The PypeIt file serves as a de-facto log file. When the sorting of that file is arbitrary, it makes it very difficult to figure out what you have observed, and organize other pypeit files. For that reason the MJD sorting needs to stay. A filename sort is not going to achieve these goals, as that will not guarantee that the PypeIt file has the images in the order in which they were acquired. 

So we need to come up with a substitute when a file is corrupt or does not have an MJD. Can you guys clarify whether the issue here is what to put in the fitstable or is it rather how to write out the pypeit file. Note the PypeIt file does not write out MJD information. 

Joe

**Comment by profxj** [comment]
Since this PR has sat stale for over 3 weeks @jhennawi I have nearly
forgotten the issue.  But the `sort` command you inserted fails because
there are `None` values that cannot be sorted.

**Comment by jhennawi** [comment]
Hi @profx, the PR is stale because you never responded to my feedback on it;) The MJD sort command needs to be in their from my perspective so that the PypeIt file delivers the data sorted by when it is taken. Otherwise the PypeIt file is a hot mess of unsorted filenames and figuring out how to organize the calibrations is a huge pain. I suggest you find another work around for these bad MJDs as I suggested originally.

**Comment by jhennawi** [comment]
See issue #779

**Pull request closed without merging**
