### PR TITLE
Allow specification of extinction file for flux calibration

### PR DESCRIPTION
**Pull request by tbowers7**
Following a suggestion from @jhennawi, this PR addresses the (rare) case when an observatory extinction file is not found within 5º (geographical coordinates) of the subject data's location.  Previously, a `None` was emitted that caused an opaque downstream exception.  With this PR, a sensible error message is now emitted instructing the user what to do.

Changes included in this PR:
* Add a new parameter `extinct_file` to BOTH **SensfuncUVISPar** and **FluxCalibrationPar** specifying how the code is to find an extinction file.  The default is `"closest"`, which was the pervious behavior.  Otherwise, a user may specify which extinction file to use from the list in `pypeit/data/extinction/README`.
* If `extinct_file = "closest"` and there are no observatory files within the 5º radius, a sensible error message is emitted.  This is in the function `pypeit.core.flux_calib.load_extinction_data()`.
* Conformal changes to the upstream routines to pass down the new parameters to `load_extinction_data()`.
* Add script `pypeit_install_extinctfile` to allow for user-supplied extinction files (installed in the user's PypeIt cache).
* Changes to `pypeit.data.utils` to search the PypeIt cache for extinction files.
* Updates to the tests of `pypeit.core.flux_calib.load_extinction_data()` to check various failure modes.
* Inclusion of @rcooke-ast's addition of `msgs.pypeitpar` from be4b92428e1135f6d3e9995d36964843da704161
* Updates to the Fluxing documentation, including addition of a discussion of extinction correction and a slight reordering of topics in the document for better flow.
-----
Example of the new "sensible error message" emitted from `pypeit.core.flux_calib.load_extinction_data()`:
```
[WARNING] :: No observatory extinction file was found within 5.0 deg
             of observation at lon = 180.0 lat = -90.0  You may
             select an included extinction file (e.g., KPNO) for use by
             adding the following to the Sensitivity Input File
             (for pypeit_sensfunc):
             [sensfunc]
               [[UVIS]]
                 extinct_file = kpnoextinct.dat
[WARNING] :: or the following to the Flux File (for pypeit_flux_calib):
             [fluxcalib]
               extinct_file = kpnoextinct.dat

[ERROR]   :: See instructions at
             https://pypeit.readthedocs.io/en/latest/fluxing.html#extinction-correction
             for using extinction files and how to install a user-supplied
             file, if desired.

```
-----
Pypeit Unit Tests and Dev Suite Unit Tests all pass:
```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  201 passed, 1275 warnings in 224.51s (0:03:44) ---
--- PYTEST UNIT TESTS PASSED  115 passed, 1894 warnings in 1261.38s (0:21:01) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 0/0 TESTS  ---
Testing Started at 2022-09-15T14:49:05.251146
Testing Completed at 2022-09-15T15:13:54.057899
Total Time: 0:24:48.806753
```
A #cloud dev-suite run will be requested after other PR's clear.

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Great stuff and thanks for the tests and docs too!

**Review by feigewang — APPROVED** [review]
Wow. I read through the changes and really appreciate for the well documented changes. 
Thanks @tbowers7

**Comment by tbowers7** [comment]
A #cloud `dev-suite` run has been requested... results to be posted here upon completion.

**Comment by tbowers7** [comment]
There was one failure in a VET test, which is addressed in 9b8bca882c35c2617b63db6e622ae9b4265e785a (above).  VET test being rerun to check for passing.
```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  201 passed, 1195 warnings in 505.06s (0:08:25) ---
--- PYTEST UNIT TESTS PASSED  118 passed, 1803 warnings in 2225.26s (0:37:05) ---
--- PYTEST VET TESTS FAILED  1 failed, 24 passed, 1191 warnings in 728.46s (0:12:08) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 153/153 TESTS  ---
Testing Started at 2022-09-22T20:12:52.075439
Testing Completed at 2022-09-23T15:59:02.602100
Total Time: 19:46:10.526661
```

**Comment by badpandabear** [comment]
Devsuite passed: 
```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  201 passed, 1181 warnings in 462.32s (0:07:42) ---
--- PYTEST UNIT TESTS PASSED  118 passed, 1793 warnings in 2382.57s (0:39:42) ---
--- PYTEST VET TESTS PASSED  25 passed, 1566 warnings in 1503.37s (0:25:03) ---
--- PYPEIT DEVELOPMENT SUITE PASSED 153/153 TESTS  ---
Testing Started at 2022-09-23T20:18:29.544049
Testing Completed at 2022-09-24T16:25:44.186217
Total Time: 20:07:14.642168
upload: ./pypeit.report to s3://pypeit/Reports/devsuite-ui_and_extinctfile-sep23.report
```

**Pull request merged**
