### PR TITLE
Pattern with speed

### PR DESCRIPTION
**Pull request by rcooke-ast**
Significant speed (and data quality) improvements to detector pattern calculation and removal. This will help speed up the reduction of KCWI data in the dev suite.

### CODE REVIEW

**Review by jhennawi — APPROVED** [review]
Looks good!

**Review by profxj — APPROVED** [review]
I'll admit I don't follow the code, but I am approving anyways..  :)

**Comment by rcooke-ast** [comment]
Thanks for the comments - I've added some extra comments + docs to explain what is going on  :-)

Just running the tests again to be sure everything is in good order.

**Comment by rcooke-ast** [comment]
I think the tests are all good, but I probably shouldn't have upgraded to cooked v1.8.3? The first failure is fixed in PR #1384, and the rest appear to be due to me running tests on the wrong cooked...
image

**Comment by rcooke-ast** [comment]
Yep - same problem with develop... + the problem with cooked...
image

**Comment by rcooke-ast** [comment]
I'm not touching anything to do with specobj, so I think it's safe to merge.

**Pull request merged**
