### PR TITLE
Calibration group numbers

### PR DESCRIPTION
**Pull request by kbwestfall**
Small PR that allows calibrations groups to be any integer.  Removes the requirement that they be a sequential number starting with 0.  This will likely affect the "master_key", but all the pypeit file functionality is the same.

### CODE REVIEW

**Review by badpandabear — APPROVED** [review]

**Review by profxj — APPROVED** [review]
all good, thx!

**Comment by kbwestfall** [comment]
Lots of dev-suite test failures.  Need to fix and rerun.

**Comment by kbwestfall** [comment]
Slowly getting there...

```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  206 passed, 136 warnings in 196.43s (0:03:16) ---
--- PYTEST UNIT TESTS PASSED  118 passed, 239 warnings in 891.85s (0:14:51) ---
--- PYTEST VET TESTS FAILED  1 failed, 31 passed, 9 warnings in 837.58s (0:13:57) ---
--- PYPEIT DEVELOPMENT SUITE FAILED 3/172 TESTS  ---
Failed tests:
    gemini_gmos/GS_HAM_R400_860 pypeit standards
    mmt_mmirs/HK_zJ pypeit
    keck_mosfire/Y_long pypeit_ql
Skipped tests:
    gemini_gmos/GS_HAM_R400_860 pypeit_sensfunc
    gemini_gmos/GS_HAM_R400_860 pypeit_flux_setup
    gemini_gmos/GS_HAM_R400_860 pypeit_flux
Testing Started at 2023-03-08T22:44:08.681839
Testing Completed at 2023-03-09T06:54:31.212450
Total Time: 8:10:22.530611
```

**Comment by kbwestfall** [comment]
Making much more significant changes.  Will close and reopen.

**Pull request closed without merging**
