### PR TITLE
Change default telluric grid file to PCA file

### PR DESCRIPTION
**Pull request by freddavies**
As titled, in response to a report on the Users' Slack. While many spectrographs have a default telluric file specified, some don't, and anyone adding a new spectrograph may not think to add one. 

Another option would be to remove this default behavior entirely and require all spectrograph files to have the telgridfile specified, but I think this is a cleaner approach.  

Edit: I've now also updated the TelluricPar default for the telgridfile, since that should also catch missing telluric grids for sensitivity functions, as well. The missing telgridfile code block in the tellfit script may now be obsolete -- should it be removed entirely?

### CODE REVIEW

**Review by kbwestfall — APPROVED** [review]

**Comment by freddavies** [comment]
I've reverted the change to the default TelluricPar, because it would override spectrographs where the telgridfile has only been specified inside of the sensfunc IR pars. Tricky tricky...

**Comment by kbwestfall** [comment]
Just a heads up that something was causing the dev-suite run to not finish.  I stopped it, merged the develop branch, and restarted the dev-suite run.  Here's hoping it finished this time!

**Comment by kbwestfall** [comment]
There's a KCRM failure, but that's probably unassociated?
```
Test Summary
--------------------------------------------------------
--- PYTEST PYPEIT UNIT TESTS PASSED  242 passed, 70 warnings in 597.02s (0:09:57) ---
--- PYTEST UNIT TESTS PASSED  133 passed, 171 warnings in 1064.88s (0:17:44) ---
--- PYTEST VET TESTS PASSED  61 passed, 70 warnings in 1987.84s (0:33:07) ---
--- PYPEIT DEVELOPMENT SUITE FAILED 1/237 TESTS  ---
Failed tests:
    keck_kcrm/medium_rh3 pypeit
Skipped tests:
Testing Started at 2024-01-22T21:04:19.676372
Testing Completed at 2024-01-23T16:42:35.446899
Total Time: 19:38:15.770527
```

**Review by rcooke-ast — APPROVED** [review]
Looks good to me - I'll just note that the test failure is unrelated to this PR, and can be ignored. It will be fixed with PR #1753

**Pull request merged**
