### PR TITLE
Hotfix for bug in edgetrace

### PR DESCRIPTION
**Pull request by kbwestfall**
Fixes a minor bug in edgetrace only encountered when manually adding/removing slit edges.

### CODE REVIEW

**Comment by kbwestfall** [comment]
The only pypeit file in the dev-suite that adds or removes slits is `pypeit_files/keck_lris_blue_multi_600_4000_d680.pypeit` and this setup isn't included in the list of develop tests.  Also, the pypeit file has:

```
[calibrations]
    [[slits]]
     rm_slits = 1:1000:725
```

which should cause the code to fault because there isn't a "slits" parameter group anymore.

There are unit tests for adding/remove slits, but this bug wasn't caught.  The reason is that the bug is actually in the need to select the relevant detector when `EdgeTraceSet.auto_trace` parses the user input defining the slits to remove.

Thoughts?

**Comment by profxj** [comment]
While we could turn that instrument back on,
I suggest we either:

1. Modify one of the `GMOS` pypeit files in `develop` to eliminate a slit (there is often at least one junk)
2. Add a PypeIt file to the unit tests to be slurped in.

I somewhat prefer the latter as we might take the opportunity to test 
a wide range of parameter inputs..

**Comment by kbwestfall** [comment]
I actually suggest we do both, particularly if there's a well established case where we should be removing traces in a dev-suite run anyway.  This bug in particular would have required a test that ran `auto_trace` and tried to remove a slit, which would not have been caught by your 2nd suggestion.  But we can come up with a unit test that does this.  I can work that into this PR.

**Comment by profxj** [comment]
Thanks!  I'll volunteer to add a `rm_slits` to one of the Gemini instruments
in the DevSuite `develop`

**Comment by kbwestfall** [comment]
Okay, added a unit test to `test_scripts.py` that runs `pypeit_trace_edges` using a pypeit file that removes and adds slits.

**Pull request merged**
