### PR TITLE
SOAR file format fix

### PR DESCRIPTION
**Pull request by profxj**
The original 'raw' data files I was given were not truly raw.

This PR modifies PypeIt to handle the proper, off-the-telescope files format.

### CODE REVIEW

**Comment by profxj** [comment]
(base) profx> py.test test_load_images.py::test_load_goodman
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /data/Projects/Python/PypeIt, configfile: setup.cfg
plugins: openfiles-0.5.0, ligo.skymap-0.5.0, filter-subpackage-0.1.1, hypothesis-6.8.5, astropy-header-0.1.2, cov-2.11.1, doctestplus-0.9.0, arraydiff-0.3, remotedata-0.3.2
collected 1 item                                                               

test_load_images.py .                                                    [100%]

=============================== warnings summary ===============================
../../../../../../home/xavier/Projects/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py:1143
../../../../../../home/xavier/Projects/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py:1143
../../../../../../home/xavier/Projects/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py:1143
   DeprecationWarning: Use of .. or absolute path in a resource path is not allowed and will raise exceptions in a future release. (__init__.py:1143)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================== 1 passed, 3 warnings in 2.05s =========================

**Comment by profxj** [comment]
Pairs with https://github.com/pypeit/PypeIt-development-suite/pull/162

**Comment by profxj** [comment]
(base) profx> ./pypeit_test -t 2 develop -i soar_goodman_red
Running tests on the following instruments:
    soar_goodman_red

Reducing data from soar_goodman_red for the following setups:
    M1
    M2

Running tests in 2 parallel processes
 0 passed/ 0 failed/ 0 skipped STARTED soar_goodman_red/M1 pypeit (without masters)
 0 passed/ 0 failed/ 0 skipped STARTED soar_goodman_red/M2 pypeit (without masters)
 1 passed/ 0 failed/ 0 skipped PASSED  soar_goodman_red/M2 pypeit (without masters)
 2 passed/ 0 failed/ 0 skipped PASSED  soar_goodman_red/M1 pypeit (without masters)

--- PYPEIT DEVELOPMENT SUITE PASSED 2/2 TESTS (Masters ignored) ---
Testing Started at 2021-07-06T13:34:43.275627
Testing Completed at 2021-07-06T13:39:56.526660
Total Time: 0:05:13.251033

**Comment by profxj** [comment]
Addresses #1214

**Review by badpandabear — APPROVED** [review]

**Review by kbwestfall — APPROVED** [review]

**Pull request merged**
