### PR TITLE
Merges develop into release (1.5.0 tag)

### PR DESCRIPTION
**Pull request by kbwestfall**
As titled. Docs updated and unit tests checked (all passed).  New tag has already been pushed. Anyone can approve and merge.

### CODE REVIEW

**Review by profxj — CHANGES_REQUESTED** [review]
Will approve and merge after the DevSuite (running)
completes.

**Review by jhennawi — APPROVED** [review]
Thanks @kbwestfall

**Comment by profxj** [comment]
Run on `develop`

-------------------------

--- PYPEIT DEVELOPMENT SUITE PASSED 124/124 TESTS (Masters ignored) ---
Testing Started at 2021-08-11T17:34:27.968038
Testing Completed at 2021-08-12T05:14:21.040080
Total Time: 11:39:53.072042

**Review by profxj — APPROVED** [review]

**Review by profxj — CHANGES_REQUESTED** [review]
something is fishy on the `Marla_bugextract` branch.

halting this until it is resolved

**Comment by profxj** [comment]
One fail for the semi-frequent OBJ_ID bit:

```
Logfile:    /tmp/REDUX_OUT/gemini_gnirs/32_SB_SXD/gemini_gnirs_32_sb_sxd.test_1dcoadd.log
Process Id: 311
Start time: Thu Aug 12 23:59:20 2021
End time:   Thu Aug 12 23:59:27 2021
Duration:   0:00:07.499221
Command:    pypeit_coadd_1dspec /PypeIt-development-suite/coadd1d_files/gemini_gnirs_32_sb_sxd.coadd1d

Error Messages:

End of Log:
  File "/PypeIt/pypeit/pypmsgs.py", line 184, in error
    raise PypeItError(msg)
pypeit.pypmsgs.PypeItError: No matching objects for OBJ0658-DET01.  Odds are you input the wrong OBJID

```

**Comment by profxj** [comment]
--- PYPEIT DEVELOPMENT SUITE FAILED 1/122 TESTS (Masters ignored) ---

**Review by profxj — APPROVED** [review]
Good to go, even with the 1 test fail.

**Pull request merged**
