### PR TITLE
Frame-typing docs

### PR DESCRIPTION
**Pull request by kbwestfall**
PR provides some added discussion to the frame-typing doc and does some minor clean-up of the front-end.  This was all geared toward ensuring that the frame-typing of DEIMOS calibration data is correct for all data in the DevSuite.

Tests pass.  I haven't run the DevSuite, but I can if suggested.  There's an associated DevSuite PR.

```
======================= 245 passed in 913.53s (0:15:13) ========================
```

### CODE REVIEW

**Review by profxj — APPROVED** [review]
Thanks for this!

My only request is that we add text in the `deimos.rst` doc (maybe rename to `keck_deimos.rst`
on frametyping.  My thinking is that SA's at WMKO (and DEIMOS users) will be advised to refer to those pages first.  

So, you might either move some (most) of the DEIMOS-specific text you put into `frametype.rst` or write a short blurb in `deimos.rst` and cross-reference the key blocks in `frametype.rst`.

I'm fine either way.

**Comment by kbwestfall** [comment]
Tests still pass:
```
========================= 246 passed in 964.30s (0:16:04) ======================
```

And I'm re-running the dev-suite on the DEIMOS data just to be sure.  Should hopefully finish by tomorrow, and then this branch can finally be merged.

**Comment by kbwestfall** [comment]
DEIMOS passes.  Ready to be merged:

```
--- PYPEIT DEVELOPMENT SUITE PASSED 7/7 TESTS (Masters ignored) ---
```

**Review by rcooke-ast — APPROVED** [review]
Looks good to me, although @jhennawi may want to look at it!

**Comment by finagle29** [comment]
Updating the linetools requirement broke ``check_requirements.py`` since linetools internally defines its version as 0.3.dev (see https://github.com/linetools/linetools/blob/master/setup.py#L50). I can see a couple ways to fix this
* linetools puts out a new release with its version correctly defined in setup.py and we require exactly that version or at least that version
* pypeit requires linetools>=0.3

**Comment by kbwestfall** [comment]
Oy.  @profxj , can you convince the `linetools` folks to follow @finagle29 's first option?  I fear more headaches with readthedocs if we follow option 2.  E.g.:

```
$ pip3 install linetools==0.3
ERROR: Could not find a version that satisfies the requirement linetools==0.3 (from versions: 0.3.dev2130, 0.3.dev2147)
ERROR: No matching distribution found for linetools==0.3
```

**Comment by finagle29** [comment]
Actually, on further inspection this might just be a problem with the conda-forge distribution of linetools. I'll do some more digging, but I think linetools itself is fine.

**Comment by finagle29** [comment]
Okay, this is actually a problem with how linetools builds from sdists. So ``pip install linetools --no-binary :all:`` and ``conda install -c conda-forge linetools`` will both install linetools 0.3.dev2147, but these installed versions of linetools will report their version as 0.3.dev0. I can look into making a PR for linetools to fix the reported version when installed from sdist. We'd have to wait for that to get merged and a new version of linetools to be released before pypeit depending on a more specific version of linetools will work on from a conda-forge installation.

Alternatively, I can submit a PR to conda-forge/linetools-feedstock that make the conda-forge package build from the linetools wheel since it is platform independent. I'm not totally sure that that'll work, but if it does, it's probably the easiest way of resolving this on our end (though linetools sdists will still have incorrect reported versions, it's maybe not important since linetools is platform-independent and thus can be installed from a wheel anywhere).

**Comment by profxj** [comment]
If you can make a PR to linetools, that would be great.
I'd merge it right away.

**Comment by finagle29** [comment]
Should be fixed by linetools/linetools#520

**Comment by finagle29** [comment]
@profxj can you make a new linetools release (0.3.dev20whatever) and push it to pypi?

**Pull request merged**
